disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  #- large_tuple
  - type_body_length
  - function_body_length
  - identifier_name
  - function_parameter_count
  - type_name 
  - force_cast
  - line_length
  - trailing_whitespace
  - valid_ibinspectable
  - block_based_kvo
  - unused_setter_value
  - for_where
