/*****************************************************************************
 * Copyright (c) 2016, 2017, 2018, 2019 joshua.tee@gmail.com. All rights reserved.
 *
 * Refer to the COPYING file of the official project for license.
 *****************************************************************************/

final class UtilityPref {

    static func prefInitNWSLoc() {
        let value = Utility.readPref("NWS_LOCATION_JSJ", "")
        if value == "" {
            Utility.writePref("NWS_LOCATION_AFC", "AK, Anchorage")
            Utility.writePref("NWS_LOCATION_AFG", "AK, Fairbanks")
            Utility.writePref("NWS_LOCATION_AJK", "AK, Juneau")
            Utility.writePref("NWS_LOCATION_ANC", "AK, Anchorage")
            Utility.writePref("NWS_LOCATION_BMX", "AL, Birmingham")
            Utility.writePref("NWS_LOCATION_HUN", "AL, Huntsville")
            Utility.writePref("NWS_LOCATION_MOB", "AL, Mobile")
            Utility.writePref("NWS_LOCATION_LZK", "AR, Little Rock")
            Utility.writePref("NWS_LOCATION_FGZ", "AZ, Flagstaff")
            Utility.writePref("NWS_LOCATION_PSR", "AZ, Phoenix")
            Utility.writePref("NWS_LOCATION_TWC", "AZ, Tucson")
            Utility.writePref("NWS_LOCATION_EKA", "CA, Eureka")
            Utility.writePref("NWS_LOCATION_HNX", "CA, Hanford")
            Utility.writePref("NWS_LOCATION_LOX", "CA, Los Angeles")
            Utility.writePref("NWS_LOCATION_MTR", "CA, San Francisco")
            Utility.writePref("NWS_LOCATION_SGX", "CA, San Diego")
            Utility.writePref("NWS_LOCATION_STO", "CA, Sacramento")
            Utility.writePref("NWS_LOCATION_BOU", "CO, Denver/Boulder")
            Utility.writePref("NWS_LOCATION_GJT", "CO, Grand Junction")
            Utility.writePref("NWS_LOCATION_PUB", "CO, Pueblo")
            Utility.writePref("NWS_LOCATION_JAX", "FL, Jacksonville")
            Utility.writePref("NWS_LOCATION_KEY", "FL, Key West")
            Utility.writePref("NWS_LOCATION_MFL", "FL, Miami")
            Utility.writePref("NWS_LOCATION_MLB", "FL, Melbourne")
            Utility.writePref("NWS_LOCATION_TAE", "FL, Tallahassee")
            Utility.writePref("NWS_LOCATION_TBW", "FL, Tampa Bay")
            Utility.writePref("NWS_LOCATION_FFC", "GA, Atlanta")
            Utility.writePref("NWS_LOCATION_GUM", "GU, Guam")
            Utility.writePref("NWS_LOCATION_HFO", "HI, Honolulu")
            Utility.writePref("NWS_LOCATION_DMX", "IA, Des Moines")
            Utility.writePref("NWS_LOCATION_DVN", "IA, Quad Cities")
            Utility.writePref("NWS_LOCATION_BOI", "ID, Boise")
            Utility.writePref("NWS_LOCATION_PIH", "ID, Pocatello")
            Utility.writePref("NWS_LOCATION_ILX", "IL, Lincoln")
            Utility.writePref("NWS_LOCATION_LOT", "IL, Chicago")
            Utility.writePref("NWS_LOCATION_IND", "IN, Indianapolis")
            Utility.writePref("NWS_LOCATION_IWX", "IN, Nrn. Indiana")
            Utility.writePref("NWS_LOCATION_DDC", "KS, Dodge City")
            Utility.writePref("NWS_LOCATION_GLD", "KS, Goodland")
            Utility.writePref("NWS_LOCATION_ICT", "KS, Wichita")
            Utility.writePref("NWS_LOCATION_TOP", "KS, Topeka")
            Utility.writePref("NWS_LOCATION_JKL", "KY, Jackson")
            Utility.writePref("NWS_LOCATION_LMK", "KY, Louisville")
            Utility.writePref("NWS_LOCATION_PAH", "KY, Paducah")
            Utility.writePref("NWS_LOCATION_LCH", "LA, Lake Charles")
            Utility.writePref("NWS_LOCATION_LIX", "LA, New Orleans")
            Utility.writePref("NWS_LOCATION_SHV", "LA, Shreveport")
            Utility.writePref("NWS_LOCATION_BOX", "MA, Boston")
            Utility.writePref("NWS_LOCATION_CAR", "ME, Caribou")
            Utility.writePref("NWS_LOCATION_GYX", "ME, Gray")
            Utility.writePref("NWS_LOCATION_APX", "MI, Gaylord")
            Utility.writePref("NWS_LOCATION_DTX", "MI, Detroit")
            Utility.writePref("NWS_LOCATION_GRR", "MI, Grand Rapids")
            Utility.writePref("NWS_LOCATION_MQT", "MI, Marquette")
            Utility.writePref("NWS_LOCATION_DLH", "MN, Duluth")
            Utility.writePref("NWS_LOCATION_MPX", "MN, Twin Cities")
            Utility.writePref("NWS_LOCATION_EAX", "MO, Kansas City")
            Utility.writePref("NWS_LOCATION_LSX", "MO, St. Louis")
            Utility.writePref("NWS_LOCATION_SGF", "MO, Springfield")
            Utility.writePref("NWS_LOCATION_JAN", "MS, Jackson")
            Utility.writePref("NWS_LOCATION_BYZ", "MT, Billings")
            Utility.writePref("NWS_LOCATION_GGW", "MT, Glasgow")
            Utility.writePref("NWS_LOCATION_MSO", "MT, Missoula")
            Utility.writePref("NWS_LOCATION_TFX", "MT, Great Falls")
            Utility.writePref("NWS_LOCATION_ILM", "NC, Wilmington")
            Utility.writePref("NWS_LOCATION_MHX", "NC, Morehead City")
            Utility.writePref("NWS_LOCATION_RAH", "NC, Raleigh")
            Utility.writePref("NWS_LOCATION_BIS", "ND, Bismarck")
            Utility.writePref("NWS_LOCATION_FGF", "ND, Grand Forks")
            Utility.writePref("NWS_LOCATION_GID", "NE, Hastings")
            Utility.writePref("NWS_LOCATION_LBF", "NE, North Platte")
            Utility.writePref("NWS_LOCATION_OAX", "NE, Omaha")
            Utility.writePref("NWS_LOCATION_PHI", "NJ, Mount Holly")
            Utility.writePref("NWS_LOCATION_ABQ", "NM, Albuquerque")
            Utility.writePref("NWS_LOCATION_LKN", "NV, Elko")
            Utility.writePref("NWS_LOCATION_REV", "NV, Reno")
            Utility.writePref("NWS_LOCATION_VEF", "NV, Las Vegas")
            Utility.writePref("NWS_LOCATION_ALY", "NY, Albany")
            Utility.writePref("NWS_LOCATION_BGM", "NY, Binghamton")
            Utility.writePref("NWS_LOCATION_BUF", "NY, Buffalo")
            Utility.writePref("NWS_LOCATION_OKX", "NY, New York City")
            Utility.writePref("NWS_LOCATION_CLE", "OH, Cleveland")
            Utility.writePref("NWS_LOCATION_ILN", "OH, Wilmington")
            Utility.writePref("NWS_LOCATION_OUN", "OK, Norman")
            Utility.writePref("NWS_LOCATION_TSA", "OK, Tulsa")
            Utility.writePref("NWS_LOCATION_MFR", "OR, Medford")
            Utility.writePref("NWS_LOCATION_PDT", "OR, Pendleton")
            Utility.writePref("NWS_LOCATION_PQR", "OR, Portland")
            Utility.writePref("NWS_LOCATION_CTP", "PA, State College")
            Utility.writePref("NWS_LOCATION_PBZ", "PA, Pittsburgh")
            Utility.writePref("NWS_LOCATION_SJU", "PR, San Juan")
            Utility.writePref("NWS_LOCATION_JSJ", "PR, San Juan")
            Utility.writePref("NWS_LOCATION_CAE", "SC, Columbia")
            Utility.writePref("NWS_LOCATION_CHS", "SC, Charleston")
            Utility.writePref("NWS_LOCATION_GSP", "SC, Greer")
            Utility.writePref("NWS_LOCATION_ABR", "SD, Aberdeen")
            Utility.writePref("NWS_LOCATION_FSD", "SD, Sioux Falls")
            Utility.writePref("NWS_LOCATION_UNR", "SD, Rapid City")
            Utility.writePref("NWS_LOCATION_MEG", "TN, Memphis")
            Utility.writePref("NWS_LOCATION_MRX", "TN, Morristown")
            Utility.writePref("NWS_LOCATION_OHX", "TN, Nashville")
            Utility.writePref("NWS_LOCATION_AMA", "TX, Amarillo")
            Utility.writePref("NWS_LOCATION_BRO", "TX, Brownsville")
            Utility.writePref("NWS_LOCATION_CRP", "TX, Corpus Christi")
            Utility.writePref("NWS_LOCATION_EPZ", "TX, El Paso")
            Utility.writePref("NWS_LOCATION_EWX", "TX, Austin")
            Utility.writePref("NWS_LOCATION_FWD", "TX, Dallas")
            Utility.writePref("NWS_LOCATION_HGX", "TX, Houston")
            Utility.writePref("NWS_LOCATION_LUB", "TX, Lubbock")
            Utility.writePref("NWS_LOCATION_MAF", "TX, Midland")
            Utility.writePref("NWS_LOCATION_SJT", "TX, San Angelo")
            Utility.writePref("NWS_LOCATION_SLC", "UT, Salt Lake City")
            Utility.writePref("NWS_LOCATION_AKQ", "VA, Wakefield")
            Utility.writePref("NWS_LOCATION_LWX", "VA, Sterling")
            Utility.writePref("NWS_LOCATION_RNK", "VA, Blacksburg")
            Utility.writePref("NWS_LOCATION_BTV", "VT, Burlington")
            Utility.writePref("NWS_LOCATION_OTX", "WA, Spokane")
            Utility.writePref("NWS_LOCATION_SEW", "WA, Seattle")
            Utility.writePref("NWS_LOCATION_ARX", "WI, La Crosse")
            Utility.writePref("NWS_LOCATION_GRB", "WI, Green Bay")
            Utility.writePref("NWS_LOCATION_MKX", "WI, Milwaukee")
            Utility.writePref("NWS_LOCATION_RLX", "WV, Charleston")
            Utility.writePref("NWS_LOCATION_CYS", "WY, Cheyenne")
            Utility.writePref("NWS_LOCATION_RIW", "WY, Riverton")
        }
    }

    static func prefInitBig() {
        let value = Utility.readPref("NWS_RID_JSJ", "")
        if value == "" {
            Utility.writePref("NWS_RID_ABQ", "ABX")
            Utility.writePref("NWS_RID_ABR", "ABR")
            Utility.writePref("NWS_RID_AFC", "AHG")
            Utility.writePref("NWS_RID_AFG", "APD")
            Utility.writePref("NWS_RID_AJK", "ACG")
            Utility.writePref("NWS_RID_AKQ", "AKQ")
            Utility.writePref("NWS_RID_ALY", "ENX")
            Utility.writePref("NWS_RID_AMA", "AMA")
            Utility.writePref("NWS_RID_ANC", "ANC")
            Utility.writePref("NWS_RID_APX", "APX")
            Utility.writePref("NWS_RID_ARX", "ARX")
            Utility.writePref("NWS_RID_BGM", "BGM")
            Utility.writePref("NWS_RID_BIS", "BIS")
            Utility.writePref("NWS_RID_BMX", "BMX")
            Utility.writePref("NWS_RID_BOI", "CBX")
            Utility.writePref("NWS_RID_BOU", "FTG")
            Utility.writePref("NWS_RID_BOX", "BOX")
            Utility.writePref("NWS_RID_BRO", "BRO")
            Utility.writePref("NWS_RID_BTV", "CXX")
            Utility.writePref("NWS_RID_BUF", "BUF")
            Utility.writePref("NWS_RID_BYZ", "BLX")
            Utility.writePref("NWS_RID_CAE", "CAE")
            Utility.writePref("NWS_RID_CAR", "CBW")
            Utility.writePref("NWS_RID_CHS", "CLX")
            Utility.writePref("NWS_RID_CLE", "CLE")
            Utility.writePref("NWS_RID_CRP", "CRP")
            Utility.writePref("NWS_RID_CTP", "CCX")
            Utility.writePref("NWS_RID_CYS", "CYS")
            Utility.writePref("NWS_RID_DDC", "DDC")
            Utility.writePref("NWS_RID_DLH", "DLH")
            Utility.writePref("NWS_RID_DMX", "DMX")
            Utility.writePref("NWS_RID_DTX", "DTX")
            Utility.writePref("NWS_RID_DVN", "DVN")
            Utility.writePref("NWS_RID_EAX", "EAX")
            Utility.writePref("NWS_RID_EKA", "BHX")
            Utility.writePref("NWS_RID_EPZ", "EPZ")
            Utility.writePref("NWS_RID_EWX", "EWX")
            Utility.writePref("NWS_RID_FFC", "FFC")
            Utility.writePref("NWS_RID_FGF", "MVX")
            Utility.writePref("NWS_RID_FGZ", "FSX")
            Utility.writePref("NWS_RID_FSD", "FSD")
            Utility.writePref("NWS_RID_FWD", "FWS")
            Utility.writePref("NWS_RID_GGW", "GGW")
            Utility.writePref("NWS_RID_GID", "UEX")
            Utility.writePref("NWS_RID_GJT", "GJX")
            Utility.writePref("NWS_RID_GLD", "GLD")
            Utility.writePref("NWS_RID_GRB", "GRB")
            Utility.writePref("NWS_RID_GRR", "GRR")
            Utility.writePref("NWS_RID_GSP", "GSP")
            Utility.writePref("NWS_RID_GUM", "GUA")
            Utility.writePref("NWS_RID_GYX", "GYX")
            Utility.writePref("NWS_RID_HFO", "HMO")
            Utility.writePref("NWS_RID_HGX", "HGX")
            Utility.writePref("NWS_RID_HNX", "HNX")
            Utility.writePref("NWS_RID_HUN", "HTX")
            Utility.writePref("NWS_RID_ICT", "ICT")
            Utility.writePref("NWS_RID_ILM", "LTX")
            Utility.writePref("NWS_RID_ILN", "ILN")
            Utility.writePref("NWS_RID_ILX", "ILX")
            Utility.writePref("NWS_RID_IND", "IND")
            Utility.writePref("NWS_RID_IWX", "IWX")
            Utility.writePref("NWS_RID_JAN", "DGX")
            Utility.writePref("NWS_RID_JAX", "JAX")
            Utility.writePref("NWS_RID_JKL", "JKL")
            Utility.writePref("NWS_RID_KEY", "BYX")
            Utility.writePref("NWS_RID_LBF", "LNX")
            Utility.writePref("NWS_RID_LCH", "LCH")
            Utility.writePref("NWS_RID_LIX", "LIX")
            Utility.writePref("NWS_RID_LKN", "LRX")
            Utility.writePref("NWS_RID_LMK", "LVX")
            Utility.writePref("NWS_RID_LOT", "LOT")
            Utility.writePref("NWS_RID_LOX", "VTX")
            Utility.writePref("NWS_RID_LSX", "LSX")
            Utility.writePref("NWS_RID_LUB", "LBB")
            Utility.writePref("NWS_RID_LWX", "LWX")
            Utility.writePref("NWS_RID_LZK", "LZK")
            Utility.writePref("NWS_RID_MAF", "MAF")
            Utility.writePref("NWS_RID_MEG", "NQA")
            Utility.writePref("NWS_RID_MFL", "AMX")
            Utility.writePref("NWS_RID_MFR", "MAX")
            Utility.writePref("NWS_RID_MHX", "MHX")
            Utility.writePref("NWS_RID_MKX", "MKX")
            Utility.writePref("NWS_RID_MLB", "MLB")
            Utility.writePref("NWS_RID_MOB", "MOB")
            Utility.writePref("NWS_RID_MPX", "MPX")
            Utility.writePref("NWS_RID_MQT", "MQT")
            Utility.writePref("NWS_RID_MRX", "MRX")
            Utility.writePref("NWS_RID_MSO", "MSX")
            Utility.writePref("NWS_RID_MTR", "MUX")
            Utility.writePref("NWS_RID_OAX", "OAX")
            Utility.writePref("NWS_RID_OHX", "OHX")
            Utility.writePref("NWS_RID_OKX", "OKX")
            Utility.writePref("NWS_RID_OTX", "OTX")
            Utility.writePref("NWS_RID_OUN", "TLX")
            Utility.writePref("NWS_RID_PAH", "PAH")
            Utility.writePref("NWS_RID_PBZ", "PBZ")
            Utility.writePref("NWS_RID_PDT", "PDT")
            Utility.writePref("NWS_RID_PHI", "DIX")
            Utility.writePref("NWS_RID_PIH", "SFX")
            Utility.writePref("NWS_RID_PQR", "RTX")
            Utility.writePref("NWS_RID_PSR", "IWA")
            Utility.writePref("NWS_RID_PUB", "PUX")
            Utility.writePref("NWS_RID_RAH", "RAX")
            Utility.writePref("NWS_RID_REV", "RGX")
            Utility.writePref("NWS_RID_RIW", "RIW")
            Utility.writePref("NWS_RID_RLX", "RLX")
            Utility.writePref("NWS_RID_RNK", "FCX")
            Utility.writePref("NWS_RID_SEW", "ATX")
            Utility.writePref("NWS_RID_SGF", "SGF")
            Utility.writePref("NWS_RID_SGX", "NKX")
            Utility.writePref("NWS_RID_SHV", "SHV")
            Utility.writePref("NWS_RID_SJT", "SJT")
            Utility.writePref("NWS_RID_SJU", "JUA")
            Utility.writePref("NWS_RID_JSJ", "JUA")
            Utility.writePref("NWS_RID_SLC", "MTX")
            Utility.writePref("NWS_RID_STO", "DAX")
            Utility.writePref("NWS_RID_TAE", "TLH")
            Utility.writePref("NWS_RID_TBW", "TBW")
            Utility.writePref("NWS_RID_TFX", "TFX")
            Utility.writePref("NWS_RID_TOP", "TWX")
            Utility.writePref("NWS_RID_TSA", "INX")
            Utility.writePref("NWS_RID_TWC", "EMX")
            Utility.writePref("NWS_RID_UNR", "UDX")
            Utility.writePref("NWS_RID_VEF", "ESX")
            Utility.writePref("STATE_TW_ID_AL", "410946082747596800")
            Utility.writePref("STATE_TW_ID_AK", "410946674685509632")
            Utility.writePref("STATE_TW_ID_AZ", "410946812913008640")
            Utility.writePref("STATE_TW_ID_AR", "410946983583428608")
            Utility.writePref("STATE_TW_ID_CA", "410947133554966530")
            Utility.writePref("STATE_TW_ID_CO", "410947263117004802")
            Utility.writePref("STATE_TW_ID_CT", "410947401004773376")
            Utility.writePref("STATE_TW_ID_DE", "410947531611185153")
            Utility.writePref("STATE_TW_ID_FL", "410947683067498496")
            Utility.writePref("STATE_TW_ID_GA", "410947813162225664")
            Utility.writePref("STATE_TW_ID_HI", "410947943412137984")
            Utility.writePref("STATE_TW_ID_ID", "410948063646076928")
            Utility.writePref("STATE_TW_ID_IL", "410948185452838912")
            Utility.writePref("STATE_TW_ID_IN", "410948324535988224")
            Utility.writePref("STATE_TW_ID_IA", "410948449949847553")
            Utility.writePref("STATE_TW_ID_KS", "410948583387459584")
            Utility.writePref("STATE_TW_ID_KY", "410948713557663746")
            Utility.writePref("STATE_TW_ID_LA", "410948840821239810")
            Utility.writePref("STATE_TW_ID_ME", "410948966411300865")
            Utility.writePref("STATE_TW_ID_MD", "410949089140813824")
            Utility.writePref("STATE_TW_ID_MA", "410949206115762176")
            Utility.writePref("STATE_TW_ID_MI", "406095836829855744")
            Utility.writePref("STATE_TW_ID_MN", "410949323623395329")
            Utility.writePref("STATE_TW_ID_MS", "410949449737703424")
            Utility.writePref("STATE_TW_ID_MO", "410949571464806400")
            Utility.writePref("STATE_TW_ID_MT", "410949718403842048")
            Utility.writePref("STATE_TW_ID_NE", "410949838730035200")
            Utility.writePref("STATE_TW_ID_NV", "410949972331212800")
            Utility.writePref("STATE_TW_ID_NH", "410950086571474944")
            Utility.writePref("STATE_TW_ID_NJ", "410950242838646785")
            Utility.writePref("STATE_TW_ID_NM", "410950366134419457")
            Utility.writePref("STATE_TW_ID_NY", "410950487198793728")
            Utility.writePref("STATE_TW_ID_NC", "410950603993411584")
            Utility.writePref("STATE_TW_ID_ND", "410950714639138816")
            Utility.writePref("STATE_TW_ID_OH", "410950826153099264")
            Utility.writePref("STATE_TW_ID_OK", "410950956541415424")
            Utility.writePref("STATE_TW_ID_OR", "410951075554803712")
            Utility.writePref("STATE_TW_ID_PA", "410951192261316608")
            Utility.writePref("STATE_TW_ID_RI", "410951324608385026")
            Utility.writePref("STATE_TW_ID_SC", "410951462919745537")
            Utility.writePref("STATE_TW_ID_SD", "410951576107237376")
            Utility.writePref("STATE_TW_ID_TN", "410951698291507202")
            Utility.writePref("STATE_TW_ID_TX", "410951810052939777")
            Utility.writePref("STATE_TW_ID_UT", "410951924230279168")
            Utility.writePref("STATE_TW_ID_VT", "410952117885472768")
            Utility.writePref("STATE_TW_ID_VA", "410952264191205376")
            Utility.writePref("STATE_TW_ID_WA", "410952480776667136")
            Utility.writePref("STATE_TW_ID_WV", "410952602067550208")
            Utility.writePref("STATE_TW_ID_WI", "410952736549502977")
            Utility.writePref("STATE_TW_ID_WY", "410952874370162688")
        }
    }

    static func prefInitTwitterCA() {
        var value = Utility.readPref("STATE_TW_ID_bcstorm", "")
        if value == "" {
            Utility.writePref("STATE_TW_ID_bcstorm", "489578049524879360")
            Utility.writePref("STATE_TW_ID_abstorm", "489578415377231872")
            Utility.writePref("STATE_TW_ID_skstorm", "489578619665014784")
            Utility.writePref("STATE_TW_ID_mbstorm", "489578784731848704")
            Utility.writePref("STATE_TW_ID_onstorm", "489710428696481795")
            Utility.writePref("STATE_TW_ID_nbstorm", "489711021922066432")
            Utility.writePref("STATE_TW_ID_pestorm", "489710770200932352")
            Utility.writePref("STATE_TW_ID_nsstorm", "489711312742522882")
            Utility.writePref("STATE_TW_ID_nlwx", "489711657912782848")
            Utility.writePref("STATE_TW_ID_ntstorm", "489754447413641217")
            Utility.writePref("STATE_TW_ID_meteoqc", "489754142907170816")
        }
        value = Utility.readPref("STATE_TW_ID_st", "")
        if value == "" {
            Utility.writePref("STATE_TW_ID_st", "611565983380164608")
        }
    }

    static func prefInitStateCodeLookup() {
        let value = Utility.readPref("STATE_LOOKUP_District+of+Columbia", "")
        if value == "" {
            Utility.writePref("STATE_LOOKUP_Alabama", "AL")
            Utility.writePref("STATE_LOOKUP_Alaska", "AK")
            Utility.writePref("STATE_LOOKUP_Arizona", "AZ")
            Utility.writePref("STATE_LOOKUP_Arkansas", "AR")
            Utility.writePref("STATE_LOOKUP_California", "CA")
            Utility.writePref("STATE_LOOKUP_Colorado", "CO")
            Utility.writePref("STATE_LOOKUP_Connecticut", "CT")
            Utility.writePref("STATE_LOOKUP_Delaware", "DE")
            Utility.writePref("STATE_LOOKUP_District+of+Columbia", "DC")
            Utility.writePref("STATE_LOOKUP_Florida", "FL")
            Utility.writePref("STATE_LOOKUP_Georgia", "GA")
            Utility.writePref("STATE_LOOKUP_Hawaii", "HI")
            Utility.writePref("STATE_LOOKUP_Idaho", "ID")
            Utility.writePref("STATE_LOOKUP_Illinois", "IL")
            Utility.writePref("STATE_LOOKUP_Indiana", "IN")
            Utility.writePref("STATE_LOOKUP_Iowa", "IA")
            Utility.writePref("STATE_LOOKUP_Kansas", "KS")
            Utility.writePref("STATE_LOOKUP_Kentucky", "KY")
            Utility.writePref("STATE_LOOKUP_Louisiana", "LA")
            Utility.writePref("STATE_LOOKUP_Maine", "ME")
            Utility.writePref("STATE_LOOKUP_Maryland", "MD")
            Utility.writePref("STATE_LOOKUP_Massachusetts", "MA")
            Utility.writePref("STATE_LOOKUP_Michigan", "MI")
            Utility.writePref("STATE_LOOKUP_Minnesota", "MN")
            Utility.writePref("STATE_LOOKUP_Mississippi", "MS")
            Utility.writePref("STATE_LOOKUP_Missouri", "MO")
            Utility.writePref("STATE_LOOKUP_Montana", "MT")
            Utility.writePref("STATE_LOOKUP_Nebraska", "NE")
            Utility.writePref("STATE_LOOKUP_Nevada", "NV")
            Utility.writePref("STATE_LOOKUP_New+Hampshire", "NH")
            Utility.writePref("STATE_LOOKUP_New+Jersey", "NJ")
            Utility.writePref("STATE_LOOKUP_New+Mexico", "NM")
            Utility.writePref("STATE_LOOKUP_New+York", "NY")
            Utility.writePref("STATE_LOOKUP_North+Carolina", "NC")
            Utility.writePref("STATE_LOOKUP_North+Dakota", "ND")
            Utility.writePref("STATE_LOOKUP_Ohio", "OH")
            Utility.writePref("STATE_LOOKUP_Oklahoma", "OK")
            Utility.writePref("STATE_LOOKUP_Oregon", "OR")
            Utility.writePref("STATE_LOOKUP_Pennsylvania", "PA")
            Utility.writePref("STATE_LOOKUP_Rhode+Island", "RI")
            Utility.writePref("STATE_LOOKUP_South+Carolina", "SC")
            Utility.writePref("STATE_LOOKUP_South+Dakota", "SD")
            Utility.writePref("STATE_LOOKUP_Tennessee", "TN")
            Utility.writePref("STATE_LOOKUP_Texas", "TX")
            Utility.writePref("STATE_LOOKUP_Utah", "UT")
            Utility.writePref("STATE_LOOKUP_Vermont", "VT")
            Utility.writePref("STATE_LOOKUP_Virginia", "VA")
            Utility.writePref("STATE_LOOKUP_Washington", "WA")
            Utility.writePref("STATE_LOOKUP_West+Virginia", "WV")
            Utility.writePref("STATE_LOOKUP_Wisconsin", "WI")
            Utility.writePref("STATE_LOOKUP_Wyoming", "WY")
        }
    }

    static func prefInitStateCode() {
        let value = Utility.readPref("STATE_CODE_AL", "")
        if value == "" {
            Utility.writePref("STATE_CODE_AL", "MS")
            Utility.writePref("STATE_CODE_AK", "AK")
            Utility.writePref("STATE_CODE_AZ", "NM")
            Utility.writePref("STATE_CODE_AR", "MS")
            Utility.writePref("STATE_CODE_CA", "NV")
            Utility.writePref("STATE_CODE_CO", "CO_UT")
            Utility.writePref("STATE_CODE_CT", "NY")
            Utility.writePref("STATE_CODE_DE", "VA_WV")
            Utility.writePref("STATE_CODE_FL", "FL")
            Utility.writePref("STATE_CODE_GA", "SC")
            Utility.writePref("STATE_CODE_HI", "HI")
            Utility.writePref("STATE_CODE_ID", "OR_ID")
            Utility.writePref("STATE_CODE_IL", "IL_IN")
            Utility.writePref("STATE_CODE_IN", "IL_IN")
            Utility.writePref("STATE_CODE_IA", "IL")
            Utility.writePref("STATE_CODE_KS", "KS")
            Utility.writePref("STATE_CODE_KY", "IL_IN")
            Utility.writePref("STATE_CODE_LA", "Gulf_Coast")
            Utility.writePref("STATE_CODE_ME", "NY")
            Utility.writePref("STATE_CODE_MD", "VA_WV")
            Utility.writePref("STATE_CODE_MA", "NY")
            Utility.writePref("STATE_CODE_MI", "MI")
            Utility.writePref("STATE_CODE_MN", "SD")
            Utility.writePref("STATE_CODE_MS", "MS")
            Utility.writePref("STATE_CODE_MO", "KS")
            Utility.writePref("STATE_CODE_MT", "MT")
            Utility.writePref("STATE_CODE_NE", "KS")
            Utility.writePref("STATE_CODE_NV", "NV")
            Utility.writePref("STATE_CODE_NH", "NY")
            Utility.writePref("STATE_CODE_NJ", "NY")
            Utility.writePref("STATE_CODE_NM", "NM")
            Utility.writePref("STATE_CODE_NY", "NY")
            Utility.writePref("STATE_CODE_NC", "SC")
            Utility.writePref("STATE_CODE_ND", "ND")
            Utility.writePref("STATE_CODE_OH", "IL_IN")
            Utility.writePref("STATE_CODE_OK", "TX")
            Utility.writePref("STATE_CODE_OR", "OR_ID")
            Utility.writePref("STATE_CODE_PA", "NY")
            Utility.writePref("STATE_CODE_RI", "NY")
            Utility.writePref("STATE_CODE_SC", "SC")
            Utility.writePref("STATE_CODE_SD", "SD")
            Utility.writePref("STATE_CODE_TN", "IL_IN")
            Utility.writePref("STATE_CODE_TX", "TX")
            Utility.writePref("STATE_CODE_UT", "CO_UT")
            Utility.writePref("STATE_CODE_VT", "NY")
            Utility.writePref("STATE_CODE_VA", "VA_WV")
            Utility.writePref("STATE_CODE_WA", "WA_ID")
            Utility.writePref("STATE_CODE_WV", "VA_WV")
            Utility.writePref("STATE_CODE_WI", "MI")
            Utility.writePref("STATE_CODE_WY", "CO_UT")
        }
    }

    static func prefInitNWSXY() {
        let value = Utility.readPref("NWS_JAN_X", "")
        if value == "" {
            Utility.writePref("NWS_CTP_X", "40.7878")
            Utility.writePref("NWS_CTP_Y", "-77.8526")
            Utility.writePref("NWS_LMK_X", "38.1722")
            Utility.writePref("NWS_LMK_Y", "-85.7162")
            Utility.writePref("NWS_AFG_X", "64.8396")
            Utility.writePref("NWS_AFG_Y", "-147.7434")
            Utility.writePref("NWS_AFC_X", "61.2060")
            Utility.writePref("NWS_AFC_Y", "-149.7855")
            Utility.writePref("NWS_AJK_X", "58.3023")
            Utility.writePref("NWS_AJK_Y", "-134.4139")
            Utility.writePref("NWS_TOP_X", "39.0134")
            Utility.writePref("NWS_TOP_Y", "-95.7071")
            Utility.writePref("NWS_ILM_X", "39.2072")
            Utility.writePref("NWS_ILM_Y", "-77.8719")
            Utility.writePref("NWS_SJU_X", "18.4129")
            Utility.writePref("NWS_SJU_Y", "-66.0989")
            Utility.writePref("NWS_GUM_X", "13.484")
            Utility.writePref("NWS_GUM_Y", "144.7967")
            Utility.writePref("NWS_LUB_X", "33.5850")
            Utility.writePref("NWS_LUB_Y", "-101.8904")
            Utility.writePref("NWS_FWD_X", "32.6963")
            Utility.writePref("NWS_FWD_Y", "-97.0827")
            Utility.writePref("NWS_JAN_X", "32.3104")
            Utility.writePref("NWS_JAN_Y", "-90.1890")
            Utility.writePref("NWS_MFR_X", "42.3294")
            Utility.writePref("NWS_MFR_Y", "-122.8524")
            Utility.writePref("NWS_FGF_X", "47.9069")
            Utility.writePref("NWS_FGF_Y", "-97.0602")
            Utility.writePref("NWS_LBF_X", "41.1431")
            Utility.writePref("NWS_LBF_Y", "-100.7710")
            Utility.writePref("NWS_GID_X", "40.9114")
            Utility.writePref("NWS_GID_Y", "-98.3601")
            Utility.writePref("NWS_MEG_X", "35.1491")
            Utility.writePref("NWS_MEG_Y", "-90.0151")
            Utility.writePref("NWS_RNK_X", "37.2283")
            Utility.writePref("NWS_RNK_Y", "-80.4212")
            Utility.writePref("NWS_PHI_X", "39.9754")
            Utility.writePref("NWS_PHI_Y", "-75.1386")
            Utility.writePref("NWS_CAR_X", "46.85897")
            Utility.writePref("NWS_CAR_Y", "-68.01895")
            Utility.writePref("NWS_BTV_X", "44.4686")
            Utility.writePref("NWS_BTV_Y", "-73.1901")
            Utility.writePref("NWS_ALY_X", "42.6825")
            Utility.writePref("NWS_ALY_Y", "-73.7899")
            Utility.writePref("NWS_SEW_X", "47.4724")
            Utility.writePref("NWS_SEW_Y", "-122.3141")
            Utility.writePref("NWS_PQR_X", "45.5031")
            Utility.writePref("NWS_PQR_Y", "-122.6251")
            Utility.writePref("NWS_BOI_X", "43.5994")
            Utility.writePref("NWS_BOI_Y", "-116.2645")
            Utility.writePref("NWS_MSO_X", "46.8685")
            Utility.writePref("NWS_MSO_Y", "-114.0090")
            Utility.writePref("NWS_PIH_X", "42.8947")
            Utility.writePref("NWS_PIH_Y", "-112.4420")
            Utility.writePref("NWS_SLC_X", "40.7482")
            Utility.writePref("NWS_SLC_Y", "-111.9155")
            Utility.writePref("NWS_HFO_X", "21.30256")
            Utility.writePref("NWS_HFO_Y", "-157.84428")
            Utility.writePref("NWS_ABQ_X", "35.1027")
            Utility.writePref("NWS_ABQ_Y", "-106.6276")
            Utility.writePref("NWS_GJT_X", "39.0836")
            Utility.writePref("NWS_GJT_Y", "-108.5638")
            Utility.writePref("NWS_PUB_X", "38.2641")
            Utility.writePref("NWS_PUB_Y", "-104.61483")
            Utility.writePref("NWS_BOU_X", "40.0107")
            Utility.writePref("NWS_BOU_Y", "-105.2584")
            Utility.writePref("NWS_BYZ_X", "45.7778")
            Utility.writePref("NWS_BYZ_Y", "-108.5429")
            Utility.writePref("NWS_UNR_X", "44.0734")
            Utility.writePref("NWS_UNR_Y", "-103.2259")
            Utility.writePref("NWS_OUN_X", "35.4449")
            Utility.writePref("NWS_OUN_Y", "-97.5219")
            Utility.writePref("NWS_TSA_X", "36.0961")
            Utility.writePref("NWS_TSA_Y", "-95.9419")
            Utility.writePref("NWS_MFL_X", "25.7744")
            Utility.writePref("NWS_MFL_Y", "-80.1937")
            Utility.writePref("NWS_KEY_X", "24.5627")
            Utility.writePref("NWS_KEY_Y", "-81.7724")
            Utility.writePref("NWS_TAE_X", "30.4293")
            Utility.writePref("NWS_TAE_Y", "-84.2906")
            Utility.writePref("NWS_JAX_X", "30.3453")
            Utility.writePref("NWS_JAX_Y", "-81.6831")
            Utility.writePref("NWS_CHS_X", "32.7942")
            Utility.writePref("NWS_CHS_Y", "-79.9419")
            Utility.writePref("NWS_HUN_X", "34.6448")
            Utility.writePref("NWS_HUN_Y", "-86.6672")
            Utility.writePref("NWS_RAH_X", "35.77399")
            Utility.writePref("NWS_RAH_Y", "-78.64008")
            Utility.writePref("NWS_SGX_X", "32.7416")
            Utility.writePref("NWS_SGX_Y", "-117.1294")
            Utility.writePref("NWS_LOX_X", "33.8228")
            Utility.writePref("NWS_LOX_Y", "-117.9561")
            Utility.writePref("NWS_MTR_X", "37.7213")
            Utility.writePref("NWS_MTR_Y", "-122.4369")
            Utility.writePref("NWS_STO_X", "38.5678")
            Utility.writePref("NWS_STO_Y", "-121.5007")
            Utility.writePref("NWS_EKA_X", "40.7852")
            Utility.writePref("NWS_EKA_Y", "-124.1540")
            Utility.writePref("NWS_REV_X", "39.5223")
            Utility.writePref("NWS_REV_Y", "-119.8127")
            Utility.writePref("NWS_LKN_X", "40.8396")
            Utility.writePref("NWS_LKN_Y", "-115.7587")
            Utility.writePref("NWS_VEF_X", "36.1273")
            Utility.writePref("NWS_VEF_Y", "-115.1712")
            Utility.writePref("NWS_PSR_X", "33.4050")
            Utility.writePref("NWS_PSR_Y", "-112.0325")
            Utility.writePref("NWS_TWC_X", "32.1965")
            Utility.writePref("NWS_TWC_Y", "-110.9025")
            Utility.writePref("NWS_FGZ_X", "35.19502")
            Utility.writePref("NWS_FGZ_Y", "-111.65310")
            Utility.writePref("NWS_ABR_X", "45.45583")
            Utility.writePref("NWS_ABR_Y", "-98.41306")
            Utility.writePref("NWS_ABX_X", "35.14972")
            Utility.writePref("NWS_ABX_Y", "-106.82333")
            Utility.writePref("NWS_AKQ_X", "36.98389")
            Utility.writePref("NWS_AKQ_Y", "-77.0075")
            Utility.writePref("NWS_AMA_X", "35.23333")
            Utility.writePref("NWS_AMA_Y", "-101.70889")
            Utility.writePref("NWS_AMX_X", "25.61056")
            Utility.writePref("NWS_AMX_Y", "-80.41306")
            Utility.writePref("NWS_APX_X", "44.90722")
            Utility.writePref("NWS_APX_Y", "-84.71972")
            Utility.writePref("NWS_ARX_X", "43.82278")
            Utility.writePref("NWS_ARX_Y", "-91.19111")
            Utility.writePref("NWS_ATX_X", "48.19472")
            Utility.writePref("NWS_ATX_Y", "-122.49444")
            Utility.writePref("NWS_BBX_X", "39.49611")
            Utility.writePref("NWS_BBX_Y", "-121.63167")
            Utility.writePref("NWS_BGM_X", "42.19972")
            Utility.writePref("NWS_BGM_Y", "-75.985")
            Utility.writePref("NWS_BHX_X", "40.49833")
            Utility.writePref("NWS_BHX_Y", "-124.29194")
            Utility.writePref("NWS_BIS_X", "46.77083")
            Utility.writePref("NWS_BIS_Y", "-100.76028")
            Utility.writePref("NWS_BLX_X", "45.85389")
            Utility.writePref("NWS_BLX_Y", "-108.60611")
            Utility.writePref("NWS_BMX_X", "33.17194")
            Utility.writePref("NWS_BMX_Y", "-86.76972")
            Utility.writePref("NWS_BOX_X", "41.95583")
            Utility.writePref("NWS_BOX_Y", "-71.1375")
            Utility.writePref("NWS_BRO_X", "25.91556")
            Utility.writePref("NWS_BRO_Y", "-97.41861")
            Utility.writePref("NWS_BUF_X", "42.94861")
            Utility.writePref("NWS_BUF_Y", "-78.73694")
            Utility.writePref("NWS_BYX_X", "24.59694")
            Utility.writePref("NWS_BYX_Y", "-81.70333")
            Utility.writePref("NWS_CAE_X", "33.94861")
            Utility.writePref("NWS_CAE_Y", "-81.11861")
            Utility.writePref("NWS_CBW_X", "46.03917")
            Utility.writePref("NWS_CBW_Y", "-67.80694")
            Utility.writePref("NWS_CBX_X", "43.49083")
            Utility.writePref("NWS_CBX_Y", "-116.23444")
            Utility.writePref("NWS_CCX_X", "40.92306")
            Utility.writePref("NWS_CCX_Y", "-78.00389")
            Utility.writePref("NWS_CLE_X", "41.41306")
            Utility.writePref("NWS_CLE_Y", "-81.86")
            Utility.writePref("NWS_CLX_X", "32.65556")
            Utility.writePref("NWS_CLX_Y", "-81.04222")
            Utility.writePref("NWS_CRI_X", "35.2383")
            Utility.writePref("NWS_CRI_Y", "-97.4602")
            Utility.writePref("NWS_CRP_X", "27.78389")
            Utility.writePref("NWS_CRP_Y", "-97.51083")
            Utility.writePref("NWS_CXX_X", "44.51111")
            Utility.writePref("NWS_CXX_Y", "-73.16639")
            Utility.writePref("NWS_CYS_X", "41.15194")
            Utility.writePref("NWS_CYS_Y", "-104.80611")
            Utility.writePref("NWS_DAX_X", "38.50111")
            Utility.writePref("NWS_DAX_Y", "-121.67667")
            Utility.writePref("NWS_DDC_X", "37.76083")
            Utility.writePref("NWS_DDC_Y", "-99.96833")
            Utility.writePref("NWS_DFX_X", "29.2725")
            Utility.writePref("NWS_DFX_Y", "-100.28028")
            Utility.writePref("NWS_DGX_X", "32.28")
            Utility.writePref("NWS_DGX_Y", "-89.98444")
            Utility.writePref("NWS_DIX_X", "39.94694")
            Utility.writePref("NWS_DIX_Y", "-74.41111")
            Utility.writePref("NWS_DLH_X", "46.83694")
            Utility.writePref("NWS_DLH_Y", "-92.20972")
            Utility.writePref("NWS_DMX_X", "41.73111")
            Utility.writePref("NWS_DMX_Y", "-93.72278")
            Utility.writePref("NWS_DOX_X", "38.82556")
            Utility.writePref("NWS_DOX_Y", "-75.44")
            Utility.writePref("NWS_DTX_X", "42.69972")
            Utility.writePref("NWS_DTX_Y", "-83.47167")
            Utility.writePref("NWS_DVN_X", "41.61167")
            Utility.writePref("NWS_DVN_Y", "-90.58083")
            Utility.writePref("NWS_DYX_X", "32.53833")
            Utility.writePref("NWS_DYX_Y", "-99.25417")
            Utility.writePref("NWS_EAX_X", "38.81028")
            Utility.writePref("NWS_EAX_Y", "-94.26417")
            Utility.writePref("NWS_EMX_X", "31.89361")
            Utility.writePref("NWS_EMX_Y", "-110.63028")
            Utility.writePref("NWS_ENX_X", "42.58639")
            Utility.writePref("NWS_ENX_Y", "-74.06444")
            Utility.writePref("NWS_EOX_X", "31.46028")
            Utility.writePref("NWS_EOX_Y", "-85.45944")
            Utility.writePref("NWS_EPZ_X", "31.87306")
            Utility.writePref("NWS_EPZ_Y", "-106.6975")
            Utility.writePref("NWS_ESX_X", "35.70111")
            Utility.writePref("NWS_ESX_Y", "-114.89139")
            Utility.writePref("NWS_EVX_X", "30.56417")
            Utility.writePref("NWS_EVX_Y", "-85.92139")
            Utility.writePref("NWS_EWX_X", "29.70361")
            Utility.writePref("NWS_EWX_Y", "-98.02806")
            Utility.writePref("NWS_EYX_X", "35.09778")
            Utility.writePref("NWS_EYX_Y", "-117.56")
            Utility.writePref("NWS_FCX_X", "37.02417")
            Utility.writePref("NWS_FCX_Y", "-80.27417")
            Utility.writePref("NWS_FDR_X", "34.36222")
            Utility.writePref("NWS_FDR_Y", "-98.97611")
            Utility.writePref("NWS_FDX_X", "34.63528")
            Utility.writePref("NWS_FDX_Y", "-103.62944")
            Utility.writePref("NWS_FFC_X", "33.36333")
            Utility.writePref("NWS_FFC_Y", "-84.56583")
            Utility.writePref("NWS_FSD_X", "43.58778")
            Utility.writePref("NWS_FSD_Y", "-96.72889")
            Utility.writePref("NWS_FSX_X", "34.57444")
            Utility.writePref("NWS_FSX_Y", "-111.19833")
            Utility.writePref("NWS_FTG_X", "39.78667")
            Utility.writePref("NWS_FTG_Y", "-104.54528")
            Utility.writePref("NWS_FWS_X", "32.57278")
            Utility.writePref("NWS_FWS_Y", "-97.30278")
            Utility.writePref("NWS_GGW_X", "48.20639")
            Utility.writePref("NWS_GGW_Y", "-106.62417")
            Utility.writePref("NWS_GJX_X", "39.06222")
            Utility.writePref("NWS_GJX_Y", "-108.21306")
            Utility.writePref("NWS_GLD_X", "39.36694")
            Utility.writePref("NWS_GLD_Y", "-101.7")
            Utility.writePref("NWS_GRB_X", "44.49833")
            Utility.writePref("NWS_GRB_Y", "-88.11111")
            Utility.writePref("NWS_GRK_X", "30.72167")
            Utility.writePref("NWS_GRK_Y", "-97.38278")
            Utility.writePref("NWS_GRR_X", "42.89389")
            Utility.writePref("NWS_GRR_Y", "-85.54472")
            Utility.writePref("NWS_GSP_X", "34.88306")
            Utility.writePref("NWS_GSP_Y", "-82.22028")
            Utility.writePref("NWS_GWX_X", "33.89667")
            Utility.writePref("NWS_GWX_Y", "-88.32889")
            Utility.writePref("NWS_GYX_X", "43.89139")
            Utility.writePref("NWS_GYX_Y", "-70.25694")
            Utility.writePref("NWS_HDX_X", "33.07639")
            Utility.writePref("NWS_HDX_Y", "-106.12222")
            Utility.writePref("NWS_HGX_X", "29.47194")
            Utility.writePref("NWS_HGX_Y", "-95.07889")
            Utility.writePref("NWS_HNX_X", "36.31417")
            Utility.writePref("NWS_HNX_Y", "-119.63111")
            Utility.writePref("NWS_HPX_X", "36.73667")
            Utility.writePref("NWS_HPX_Y", "-87.285")
            Utility.writePref("NWS_HTX_X", "34.93056")
            Utility.writePref("NWS_HTX_Y", "-86.08361")
            Utility.writePref("NWS_ICT_X", "37.65444")
            Utility.writePref("NWS_ICT_Y", "-97.4425")
            Utility.writePref("NWS_ICX_X", "37.59083")
            Utility.writePref("NWS_ICX_Y", "-112.86222")
            Utility.writePref("NWS_ILN_X", "39.42028")
            Utility.writePref("NWS_ILN_Y", "-83.82167")
            Utility.writePref("NWS_ILX_X", "40.15056")
            Utility.writePref("NWS_ILX_Y", "-89.33667")
            Utility.writePref("NWS_IND_X", "39.7075")
            Utility.writePref("NWS_IND_Y", "-86.28028")
            Utility.writePref("NWS_INX_X", "36.175")
            Utility.writePref("NWS_INX_Y", "-95.56444")
            Utility.writePref("NWS_IWA_X", "33.28917")
            Utility.writePref("NWS_IWA_Y", "-111.66917")
            Utility.writePref("NWS_IWX_X", "41.40861")
            Utility.writePref("NWS_IWX_Y", "-85.7")
            Utility.writePref("NWS_JAX_X", "30.48444")
            Utility.writePref("NWS_JAX_Y", "-81.70194")
            Utility.writePref("NWS_JGX_X", "32.675")
            Utility.writePref("NWS_JGX_Y", "-83.35111")
            Utility.writePref("NWS_JKL_X", "37.59083")
            Utility.writePref("NWS_JKL_Y", "-83.31306")
            Utility.writePref("NWS_LBB_X", "33.65417")
            Utility.writePref("NWS_LBB_Y", "-101.81361")
            Utility.writePref("NWS_LCH_X", "30.125")
            Utility.writePref("NWS_LCH_Y", "-93.21583")
            Utility.writePref("NWS_LGX_X", "47.1158")
            Utility.writePref("NWS_LGX_Y", "-124.1069")
            Utility.writePref("NWS_LIX_X", "30.33667")
            Utility.writePref("NWS_LIX_Y", "-89.82528")
            Utility.writePref("NWS_LNX_X", "41.95778")
            Utility.writePref("NWS_LNX_Y", "-100.57583")
            Utility.writePref("NWS_LOT_X", "41.60444")
            Utility.writePref("NWS_LOT_Y", "-88.08472")
            Utility.writePref("NWS_LRX_X", "40.73972")
            Utility.writePref("NWS_LRX_Y", "-116.80278")
            Utility.writePref("NWS_LSX_X", "38.69889")
            Utility.writePref("NWS_LSX_Y", "-90.68278")
            Utility.writePref("NWS_LTX_X", "33.98917")
            Utility.writePref("NWS_LTX_Y", "-78.42917")
            Utility.writePref("NWS_LVX_X", "37.97528")
            Utility.writePref("NWS_LVX_Y", "-85.94389")
            Utility.writePref("NWS_LWX_X", "38.97628")
            Utility.writePref("NWS_LWX_Y", "-77.48751")
            Utility.writePref("NWS_LZK_X", "34.83639")
            Utility.writePref("NWS_LZK_Y", "-92.26194")
            Utility.writePref("NWS_MAF_X", "31.94333")
            Utility.writePref("NWS_MAF_Y", "-102.18889")
            Utility.writePref("NWS_MAX_X", "42.08111")
            Utility.writePref("NWS_MAX_Y", "-122.71611")
            Utility.writePref("NWS_MBX_X", "48.3925")
            Utility.writePref("NWS_MBX_Y", "-100.86444")
            Utility.writePref("NWS_MHX_X", "34.77583")
            Utility.writePref("NWS_MHX_Y", "-76.87639")
            Utility.writePref("NWS_MKX_X", "42.96778")
            Utility.writePref("NWS_MKX_Y", "-88.55056")
            Utility.writePref("NWS_MLB_X", "28.11306")
            Utility.writePref("NWS_MLB_Y", "-80.65444")
            Utility.writePref("NWS_MOB_X", "30.67944")
            Utility.writePref("NWS_MOB_Y", "-88.23972")
            Utility.writePref("NWS_MPX_X", "44.84889")
            Utility.writePref("NWS_MPX_Y", "-93.56528")
            Utility.writePref("NWS_MQT_X", "46.53111")
            Utility.writePref("NWS_MQT_Y", "-87.54833")
            Utility.writePref("NWS_MRX_X", "36.16833")
            Utility.writePref("NWS_MRX_Y", "-83.40194")
            Utility.writePref("NWS_MSX_X", "47.04111")
            Utility.writePref("NWS_MSX_Y", "-113.98611")
            Utility.writePref("NWS_MTX_X", "41.26278")
            Utility.writePref("NWS_MTX_Y", "-112.44694")
            Utility.writePref("NWS_MUX_X", "37.15528")
            Utility.writePref("NWS_MUX_Y", "-121.8975")
            Utility.writePref("NWS_MVX_X", "47.52806")
            Utility.writePref("NWS_MVX_Y", "-97.325")
            Utility.writePref("NWS_MXX_X", "32.53667")
            Utility.writePref("NWS_MXX_Y", "-85.78972")
            Utility.writePref("NWS_NKX_X", "32.91889")
            Utility.writePref("NWS_NKX_Y", "-117.04194")
            Utility.writePref("NWS_NQA_X", "35.34472")
            Utility.writePref("NWS_NQA_Y", "-89.87333")
            Utility.writePref("NWS_OAX_X", "41.32028")
            Utility.writePref("NWS_OAX_Y", "-96.36639")
            Utility.writePref("NWS_OHX_X", "36.24722")
            Utility.writePref("NWS_OHX_Y", "-86.5625")
            Utility.writePref("NWS_OKX_X", "40.86556")
            Utility.writePref("NWS_OKX_Y", "-72.86444")
            Utility.writePref("NWS_OTX_X", "47.68056")
            Utility.writePref("NWS_OTX_Y", "-117.62583")
            Utility.writePref("NWS_PAH_X", "37.06833")
            Utility.writePref("NWS_PAH_Y", "-88.77194")
            Utility.writePref("NWS_PBZ_X", "40.53167")
            Utility.writePref("NWS_PBZ_Y", "-80.21833")
            Utility.writePref("NWS_PDT_X", "45.69056")
            Utility.writePref("NWS_PDT_Y", "-118.85278")
            Utility.writePref("NWS_POE_X", "31.15528")
            Utility.writePref("NWS_POE_Y", "-92.97583")
            Utility.writePref("NWS_PUX_X", "38.45944")
            Utility.writePref("NWS_PUX_Y", "-104.18139")
            Utility.writePref("NWS_RAX_X", "35.66528")
            Utility.writePref("NWS_RAX_Y", "-78.49")
            Utility.writePref("NWS_RGX_X", "39.75417")
            Utility.writePref("NWS_RGX_Y", "-119.46111")
            Utility.writePref("NWS_RIW_X", "43.06611")
            Utility.writePref("NWS_RIW_Y", "-108.47667")
            Utility.writePref("NWS_RLX_X", "38.31194")
            Utility.writePref("NWS_RLX_Y", "-81.72389")
            Utility.writePref("NWS_RTX_X", "45.715")
            Utility.writePref("NWS_RTX_Y", "-122.96417")
            Utility.writePref("NWS_SFX_X", "43.10583")
            Utility.writePref("NWS_SFX_Y", "-112.68528")
            Utility.writePref("NWS_SGF_X", "37.23528")
            Utility.writePref("NWS_SGF_Y", "-93.40028")
            Utility.writePref("NWS_SHV_X", "32.45056")
            Utility.writePref("NWS_SHV_Y", "-93.84111")
            Utility.writePref("NWS_SJT_X", "31.37111")
            Utility.writePref("NWS_SJT_Y", "-100.49222")
            Utility.writePref("NWS_SOX_X", "33.81778")
            Utility.writePref("NWS_SOX_Y", "-117.635")
            Utility.writePref("NWS_SRX_X", "35.29056")
            Utility.writePref("NWS_SRX_Y", "-94.36167")
            Utility.writePref("NWS_TBW_X", "27.70528")
            Utility.writePref("NWS_TBW_Y", "-82.40194")
            Utility.writePref("NWS_TFX_X", "47.45972")
            Utility.writePref("NWS_TFX_Y", "-111.38444")
            Utility.writePref("NWS_TLH_X", "30.3975")
            Utility.writePref("NWS_TLH_Y", "-84.32889")
            Utility.writePref("NWS_TLX_X", "35.33306")
            Utility.writePref("NWS_TLX_Y", "-97.2775")
            Utility.writePref("NWS_TWX_X", "38.99694")
            Utility.writePref("NWS_TWX_Y", "-96.2325")
            Utility.writePref("NWS_TYX_X", "43.75583")
            Utility.writePref("NWS_TYX_Y", "-75.68")
            Utility.writePref("NWS_UDX_X", "44.125")
            Utility.writePref("NWS_UDX_Y", "-102.82944")
            Utility.writePref("NWS_UEX_X", "40.32083")
            Utility.writePref("NWS_UEX_Y", "-98.44167")
            Utility.writePref("NWS_VAX_X", "30.89")
            Utility.writePref("NWS_VAX_Y", "-83.00194")
            Utility.writePref("NWS_VBX_X", "34.83806")
            Utility.writePref("NWS_VBX_Y", "-120.39583")
            Utility.writePref("NWS_VNX_X", "36.74083")
            Utility.writePref("NWS_VNX_Y", "-98.1275")
            Utility.writePref("NWS_VTX_X", "34.41167")
            Utility.writePref("NWS_VTX_Y", "-119.17861")
            Utility.writePref("NWS_VWX_X", "38.26")
            Utility.writePref("NWS_VWX_Y", "-87.7247")
            Utility.writePref("NWS_YUX_X", "32.49528")
            Utility.writePref("NWS_YUX_Y", "-114.65583")
            Utility.writePref("NWS_PLA_X", "38.73028")
            Utility.writePref("NWS_PLA_Y", "-27.32167")
            Utility.writePref("NWS_ABC_X", "60.79278")
            Utility.writePref("NWS_ABC_Y", "-161.87417")
            Utility.writePref("NWS_ACG_X", "56.85278")
            Utility.writePref("NWS_ACG_Y", "-135.52917")
            Utility.writePref("NWS_AEC_X", "64.51139")
            Utility.writePref("NWS_AEC_Y", "-165.295")
            Utility.writePref("NWS_AHG_X", "60.725914")
            Utility.writePref("NWS_AHG_Y", "-151.35146")
            Utility.writePref("NWS_AIH_X", "59.46194")
            Utility.writePref("NWS_AIH_Y", "-146.30111")
            Utility.writePref("NWS_AKC_X", "58.67944")
            Utility.writePref("NWS_AKC_Y", "-156.62944")
            Utility.writePref("NWS_APD_X", "65.03556")
            Utility.writePref("NWS_APD_Y", "-147.49917")
            Utility.writePref("NWS_GUA_X", "13.45444")
            Utility.writePref("NWS_GUA_Y", "144.80833")
            Utility.writePref("NWS_HKI_X", "21.89417")
            Utility.writePref("NWS_HKI_Y", "-159.55222")
            Utility.writePref("NWS_HKM_X", "20.12556")
            Utility.writePref("NWS_HKM_Y", "-155.77778")
            Utility.writePref("NWS_HMO_X", "21.13278")
            Utility.writePref("NWS_HMO_Y", "-157.18")
            Utility.writePref("NWS_HWA_X", "19.095")
            Utility.writePref("NWS_HWA_Y", "-155.56889")
            Utility.writePref("NWS_KJK_X", "35.92417")
            Utility.writePref("NWS_KJK_Y", "126.62222")
            Utility.writePref("NWS_KSG_X", "36.95972")
            Utility.writePref("NWS_KSG_Y", "127.01833")
            Utility.writePref("NWS_ODN_X", "26.30194")
            Utility.writePref("NWS_ODN_Y", "127.90972")
            Utility.writePref("NWS_JUA_X", "18.1175")
            Utility.writePref("NWS_JUA_Y", "-66.07861")
        }
    }

    static func prefInitRIDXY() {
        let value = Utility.readPref("RID_ABR_Xmay14_2", "")
        if value == "" {
            Utility.writePref("RID_ABR_Xmay14_2", "45.451")
            Utility.writePref("RID_TYX_X", "43.756")
            Utility.writePref("RID_TYX_Y", "75.68")
            Utility.writePref("RID_ABR_X", "45.456")
            Utility.writePref("RID_ABR_Y", "98.413")
            Utility.writePref("RID_ENX_X", "42.586")
            Utility.writePref("RID_ENX_Y", "74.064")
            Utility.writePref("RID_ABX_X", "35.15")
            Utility.writePref("RID_ABX_Y", "106.824")
            Utility.writePref("RID_FDR_X", "34.362")
            Utility.writePref("RID_FDR_Y", "98.977")
            Utility.writePref("RID_AMA_X", "35.233")
            Utility.writePref("RID_AMA_Y", "101.709")
            Utility.writePref("RID_AHG_X", "60.726")
            Utility.writePref("RID_AHG_Y", "151.351")
            Utility.writePref("RID_GUA_X", "13.456")
            Utility.writePref("RID_GUA_Y", "144.811")
            Utility.writePref("RID_FFC_X", "33.363")
            Utility.writePref("RID_FFC_Y", "84.566")
            Utility.writePref("RID_EWX_X", "29.704")
            Utility.writePref("RID_EWX_Y", "98.029")
            Utility.writePref("RID_BBX_X", "39.496")
            Utility.writePref("RID_BBX_Y", "121.632")
            Utility.writePref("RID_ABC_X", "60.792")
            Utility.writePref("RID_ABC_Y", "161.876")
            Utility.writePref("RID_BLX_X", "45.854")
            Utility.writePref("RID_BLX_Y", "108.607")
            Utility.writePref("RID_BGM_X", "42.2")
            Utility.writePref("RID_BGM_Y", "75.985")
            Utility.writePref("RID_BMX_X", "33.171")
            Utility.writePref("RID_BMX_Y", "86.77")
            Utility.writePref("RID_BIS_X", "46.771")
            Utility.writePref("RID_BIS_Y", "100.76")
            Utility.writePref("RID_CBX_X", "43.49")
            Utility.writePref("RID_CBX_Y", "116.236")
            Utility.writePref("RID_BOX_X", "41.956")
            Utility.writePref("RID_BOX_Y", "71.137")
            Utility.writePref("RID_BRO_X", "25.916")
            Utility.writePref("RID_BRO_Y", "97.419")
            Utility.writePref("RID_BUF_X", "42.949")
            Utility.writePref("RID_BUF_Y", "78.737")
            Utility.writePref("RID_CXX_X", "44.511")
            Utility.writePref("RID_CXX_Y", "73.166")
            Utility.writePref("RID_FDX_X", "34.634")
            Utility.writePref("RID_FDX_Y", "103.619")
            Utility.writePref("RID_ICX_X", "37.591")
            Utility.writePref("RID_ICX_Y", "112.862")
            Utility.writePref("RID_CLX_X", "32.655")
            Utility.writePref("RID_CLX_Y", "81.042")
            Utility.writePref("RID_RLX_X", "38.311")
            Utility.writePref("RID_RLX_Y", "81.723")
            Utility.writePref("RID_CYS_X", "41.152")
            Utility.writePref("RID_CYS_Y", "104.806")
            Utility.writePref("RID_LOT_X", "41.604")
            Utility.writePref("RID_LOT_Y", "88.085")
            Utility.writePref("RID_ILN_X", "39.42")
            Utility.writePref("RID_ILN_Y", "83.822")
            Utility.writePref("RID_CLE_X", "41.413")
            Utility.writePref("RID_CLE_Y", "81.86")
            Utility.writePref("RID_CAE_X", "33.949")
            Utility.writePref("RID_CAE_Y", "81.119")
            Utility.writePref("RID_GWX_X", "33.897")
            Utility.writePref("RID_GWX_Y", "88.329")
            Utility.writePref("RID_CRP_X", "27.784")
            Utility.writePref("RID_CRP_Y", "97.511")
            Utility.writePref("RID_FWS_X", "32.573")
            Utility.writePref("RID_FWS_Y", "97.303")
            Utility.writePref("RID_DVN_X", "41.612")
            Utility.writePref("RID_DVN_Y", "90.581")
            Utility.writePref("RID_FTG_X", "39.786")
            Utility.writePref("RID_FTG_Y", "104.546")
            Utility.writePref("RID_DMX_X", "41.731")
            Utility.writePref("RID_DMX_Y", "93.723")
            Utility.writePref("RID_DTX_X", "42.7")
            Utility.writePref("RID_DTX_Y", "83.472")
            Utility.writePref("RID_DDC_X", "37.761")
            Utility.writePref("RID_DDC_Y", "99.969")
            Utility.writePref("RID_DOX_X", "38.826")
            Utility.writePref("RID_DOX_Y", "75.44")
            Utility.writePref("RID_DLH_X", "46.837")
            Utility.writePref("RID_DLH_Y", "92.21")
            Utility.writePref("RID_DYX_X", "32.538")
            Utility.writePref("RID_DYX_Y", "99.254")
            Utility.writePref("RID_EYX_X", "35.098")
            Utility.writePref("RID_EYX_Y", "117.561")
            Utility.writePref("RID_EVX_X", "30.565")
            Utility.writePref("RID_EVX_Y", "85.922")
            Utility.writePref("RID_EPZ_X", "31.873")
            Utility.writePref("RID_EPZ_Y", "106.698")
            Utility.writePref("RID_LRX_X", "40.74")
            Utility.writePref("RID_LRX_Y", "116.803")
            Utility.writePref("RID_BHX_X", "40.499")
            Utility.writePref("RID_BHX_Y", "124.292")
            Utility.writePref("RID_APD_X", "65.035")
            Utility.writePref("RID_APD_Y", "147.501")
            Utility.writePref("RID_FSX_X", "34.574")
            Utility.writePref("RID_FSX_Y", "111.198")
            Utility.writePref("RID_HPX_X", "36.737")
            Utility.writePref("RID_HPX_Y", "87.285")
            Utility.writePref("RID_GRK_X", "30.722")
            Utility.writePref("RID_GRK_Y", "97.383")
            Utility.writePref("RID_POE_X", "31.155")
            Utility.writePref("RID_POE_Y", "92.976")
            Utility.writePref("RID_EOX_X", "31.46")
            Utility.writePref("RID_EOX_Y", "85.459")
            Utility.writePref("RID_SRX_X", "35.29")
            Utility.writePref("RID_SRX_Y", "94.362")
            Utility.writePref("RID_IWX_X", "41.359")
            Utility.writePref("RID_IWX_Y", "85.7")
            Utility.writePref("RID_APX_X", "44.906")
            Utility.writePref("RID_APX_Y", "84.72")
            Utility.writePref("RID_GGW_X", "48.206")
            Utility.writePref("RID_GGW_Y", "106.625")
            Utility.writePref("RID_GLD_X", "39.367")
            Utility.writePref("RID_GLD_Y", "101.7")
            Utility.writePref("RID_MVX_X", "47.528")
            Utility.writePref("RID_MVX_Y", "97.325")
            Utility.writePref("RID_GJX_X", "39.062")
            Utility.writePref("RID_GJX_Y", "108.214")
            Utility.writePref("RID_GRR_X", "42.894")
            Utility.writePref("RID_GRR_Y", "85.545")
            Utility.writePref("RID_TFX_X", "47.46")
            Utility.writePref("RID_TFX_Y", "111.385")
            Utility.writePref("RID_GRB_X", "44.499")
            Utility.writePref("RID_GRB_Y", "88.111")
            Utility.writePref("RID_GSP_X", "34.883")
            Utility.writePref("RID_GSP_Y", "82.22")
            Utility.writePref("RID_UEX_X", "40.321")
            Utility.writePref("RID_UEX_Y", "98.442")
            Utility.writePref("RID_HDX_X", "33.077")
            Utility.writePref("RID_HDX_Y", "106.12")
            Utility.writePref("RID_CBW_X", "46.039")
            Utility.writePref("RID_CBW_Y", "67.806")
            Utility.writePref("RID_HGX_X", "29.472")
            Utility.writePref("RID_HGX_Y", "95.079")
            Utility.writePref("RID_HTX_X", "34.931")
            Utility.writePref("RID_HTX_Y", "86.084")
            Utility.writePref("RID_IND_X", "39.708")
            Utility.writePref("RID_IND_Y", "86.28")
            Utility.writePref("RID_JKL_X", "37.591")
            Utility.writePref("RID_JKL_Y", "83.313")
            Utility.writePref("RID_JAX_X", "30.485")
            Utility.writePref("RID_JAX_Y", "81.702")
            Utility.writePref("RID_EAX_X", "38.81")
            Utility.writePref("RID_EAX_Y", "94.264")
            Utility.writePref("RID_BYX_X", "24.597")
            Utility.writePref("RID_BYX_Y", "81.703")
            Utility.writePref("RID_AKC_X", "58.68")
            Utility.writePref("RID_AKC_Y", "156.627")
            Utility.writePref("RID_MRX_X", "36.168")
            Utility.writePref("RID_MRX_Y", "83.402")
            Utility.writePref("RID_ARX_X", "43.823")
            Utility.writePref("RID_ARX_Y", "91.191")
            Utility.writePref("RID_LCH_X", "30.125")
            Utility.writePref("RID_LCH_Y", "93.216")
            Utility.writePref("RID_ESX_X", "35.701")
            Utility.writePref("RID_ESX_Y", "114.891")
            Utility.writePref("RID_DFX_X", "29.273")
            Utility.writePref("RID_DFX_Y", "100.28")
            Utility.writePref("RID_ILX_X", "40.15")
            Utility.writePref("RID_ILX_Y", "89.337")
            Utility.writePref("RID_LZK_X", "34.836")
            Utility.writePref("RID_LZK_Y", "92.262")
            Utility.writePref("RID_VTX_X", "34.412")
            Utility.writePref("RID_VTX_Y", "119.179")
            Utility.writePref("RID_LVX_X", "37.975")
            Utility.writePref("RID_LVX_Y", "85.944")
            Utility.writePref("RID_LBB_X", "33.654")
            Utility.writePref("RID_LBB_Y", "101.814")
            Utility.writePref("RID_MQT_X", "46.531")
            Utility.writePref("RID_MQT_Y", "87.548")
            Utility.writePref("RID_MXX_X", "32.537")
            Utility.writePref("RID_MXX_Y", "85.79")
            Utility.writePref("RID_MAX_X", "42.081")
            Utility.writePref("RID_MAX_Y", "122.717")
            Utility.writePref("RID_MLB_X", "28.113")
            Utility.writePref("RID_MLB_Y", "80.654")
            Utility.writePref("RID_NQA_X", "35.345")
            Utility.writePref("RID_NQA_Y", "89.873")
            Utility.writePref("RID_AMX_X", "25.611")
            Utility.writePref("RID_AMX_Y", "80.413")
            Utility.writePref("RID_AIH_X", "59.46")
            Utility.writePref("RID_AIH_Y", "146.303")
            Utility.writePref("RID_MAF_X", "31.943")
            Utility.writePref("RID_MAF_Y", "102.189")
            Utility.writePref("RID_MKX_X", "42.968")
            Utility.writePref("RID_MKX_Y", "88.551")
            Utility.writePref("RID_MPX_X", "44.849")
            Utility.writePref("RID_MPX_Y", "93.565")
            Utility.writePref("RID_MBX_X", "48.393")
            Utility.writePref("RID_MBX_Y", "100.864")
            Utility.writePref("RID_MSX_X", "47.041")
            Utility.writePref("RID_MSX_Y", "113.986")
            Utility.writePref("RID_MOB_X", "30.679")
            Utility.writePref("RID_MOB_Y", "88.24")
            Utility.writePref("RID_HMO_X", "21.133")
            Utility.writePref("RID_HMO_Y", "157.18")
            Utility.writePref("RID_VAX_X", "30.89")
            Utility.writePref("RID_VAX_Y", "83.002")
            Utility.writePref("RID_MHX_X", "34.776")
            Utility.writePref("RID_MHX_Y", "76.876")
            Utility.writePref("RID_OHX_X", "36.247")
            Utility.writePref("RID_OHX_Y", "86.563")
            Utility.writePref("RID_LIX_X", "30.337")
            Utility.writePref("RID_LIX_Y", "89.825")
            Utility.writePref("RID_OKX_X", "40.865")
            Utility.writePref("RID_OKX_Y", "72.864")
            Utility.writePref("RID_AEC_X", "64.512")
            Utility.writePref("RID_AEC_Y", "165.293")
            Utility.writePref("RID_AKQ_X", "36.984")
            Utility.writePref("RID_AKQ_Y", "77.008")
            Utility.writePref("RID_LNX_X", "41.958")
            Utility.writePref("RID_LNX_Y", "100.576")
            Utility.writePref("RID_TLX_X", "35.333")
            Utility.writePref("RID_TLX_Y", "97.278")
            Utility.writePref("RID_OAX_X", "41.32")
            Utility.writePref("RID_OAX_Y", "96.367")
            Utility.writePref("RID_PAH_X", "37.068")
            Utility.writePref("RID_PAH_Y", "88.772")
            Utility.writePref("RID_PDT_X", "45.691")
            Utility.writePref("RID_PDT_Y", "118.853")
            Utility.writePref("RID_DIX_X", "39.947")
            Utility.writePref("RID_DIX_Y", "74.411")
            Utility.writePref("RID_IWA_X", "33.289")
            Utility.writePref("RID_IWA_Y", "111.67")
            Utility.writePref("RID_PBZ_X", "40.532")
            Utility.writePref("RID_PBZ_Y", "80.218")
            Utility.writePref("RID_SFX_X", "43.106")
            Utility.writePref("RID_SFX_Y", "112.686")
            Utility.writePref("RID_GYX_X", "43.891")
            Utility.writePref("RID_GYX_Y", "70.256")
            Utility.writePref("RID_RTX_X", "45.715")
            Utility.writePref("RID_RTX_Y", "122.965")
            Utility.writePref("RID_PUX_X", "38.46")
            Utility.writePref("RID_PUX_Y", "104.181")
            Utility.writePref("RID_RAX_X", "35.665")
            Utility.writePref("RID_RAX_Y", "78.49")
            Utility.writePref("RID_UDX_X", "44.125")
            Utility.writePref("RID_UDX_Y", "102.83")
            Utility.writePref("RID_RGX_X", "39.754")
            Utility.writePref("RID_RGX_Y", "119.462")
            Utility.writePref("RID_RIW_X", "43.066")
            Utility.writePref("RID_RIW_Y", "108.477")
            Utility.writePref("RID_FCX_X", "37.024")
            Utility.writePref("RID_FCX_Y", "80.274")
            Utility.writePref("RID_JGX_X", "32.675")
            Utility.writePref("RID_JGX_Y", "83.351")
            Utility.writePref("RID_DAX_X", "38.501")
            Utility.writePref("RID_DAX_Y", "121.678")
            Utility.writePref("RID_LSX_X", "38.699")
            Utility.writePref("RID_LSX_Y", "90.683")
            Utility.writePref("RID_MTX_X", "41.263")
            Utility.writePref("RID_MTX_Y", "112.448")
            Utility.writePref("RID_SJT_X", "31.371")
            Utility.writePref("RID_SJT_Y", "100.492")
            Utility.writePref("RID_NKX_X", "32.919")
            Utility.writePref("RID_NKX_Y", "117.041")
            Utility.writePref("RID_MUX_X", "37.155")
            Utility.writePref("RID_MUX_Y", "121.898")
            Utility.writePref("RID_HNX_X", "36.314")
            Utility.writePref("RID_HNX_Y", "119.632")
            Utility.writePref("RID_JUA_X", "18.116")
            Utility.writePref("RID_JUA_Y", "66.078")
            Utility.writePref("RID_SOX_X", "33.818")
            Utility.writePref("RID_SOX_Y", "117.636")
            Utility.writePref("RID_ATX_X", "48.195")
            Utility.writePref("RID_ATX_Y", "122.496")
            Utility.writePref("RID_SHV_X", "32.451")
            Utility.writePref("RID_SHV_Y", "93.841")
            Utility.writePref("RID_FSD_X", "43.588")
            Utility.writePref("RID_FSD_Y", "96.729")
            Utility.writePref("RID_ACG_X", "56.853")
            Utility.writePref("RID_ACG_Y", "135.528")
            Utility.writePref("RID_HKI_X", "21.894")
            Utility.writePref("RID_HKI_Y", "159.552")
            Utility.writePref("RID_HWA_X", "19.095")
            Utility.writePref("RID_HWA_Y", "155.569")
            Utility.writePref("RID_OTX_X", "47.681")
            Utility.writePref("RID_OTX_Y", "117.626")
            Utility.writePref("RID_SGF_X", "37.235")
            Utility.writePref("RID_SGF_Y", "93.4")
            Utility.writePref("RID_CCX_X", "40.923")
            Utility.writePref("RID_CCX_Y", "78.004")
            Utility.writePref("RID_LWX_X", "38.976")
            Utility.writePref("RID_LWX_Y", "77.487")
            Utility.writePref("RID_TLH_X", "30.398")
            Utility.writePref("RID_TLH_Y", "84.329")
            Utility.writePref("RID_TBW_X", "27.705")
            Utility.writePref("RID_TBW_Y", "82.402")
            Utility.writePref("RID_TWX_X", "38.997")
            Utility.writePref("RID_TWX_Y", "96.232")
            Utility.writePref("RID_EMX_X", "31.894")
            Utility.writePref("RID_EMX_Y", "110.63")
            Utility.writePref("RID_INX_X", "36.175")
            Utility.writePref("RID_INX_Y", "95.564")
            Utility.writePref("RID_VNX_X", "36.741")
            Utility.writePref("RID_VNX_Y", "98.128")
            Utility.writePref("RID_VBX_X", "34.839")
            Utility.writePref("RID_VBX_Y", "120.398")
            Utility.writePref("RID_ICT_X", "37.654")
            Utility.writePref("RID_ICT_Y", "97.443")
            Utility.writePref("RID_LTX_X", "33.989")
            Utility.writePref("RID_LTX_Y", "78.429")
            Utility.writePref("RID_YUX_X", "32.495")
            Utility.writePref("RID_YUX_Y", "114.656")
            Utility.writePref("RID_LGX_X", "47.116")
            Utility.writePref("RID_LGX_Y", "124.107")
            Utility.writePref("RID_DGX_X", "32.28")
            Utility.writePref("RID_DGX_Y", "89.984")
            Utility.writePref("RID_VWX_X", "38.26")
            Utility.writePref("RID_VWX_Y", "87.724")
            Utility.writePref("RID_HKM_X", "20.125")
            Utility.writePref("RID_HKM_Y", "155.778")
        }
    }

    static func prefInitRIDXY2() {
        let value = Utility.readPref("RID_TATL_Y", "")
        if value == "" {
            Utility.writePref("RID_aug12_4_X", "aug112014")
            Utility.writePref("RID_latest_X", "36.105")
            Utility.writePref("RID_latest_Y", "97.141")
            Utility.writePref("RID_centgrtlakes_X", "42.127")
            Utility.writePref("RID_centgrtlakes_Y", "84.544")
            Utility.writePref("RID_uppermissvly_X", "42.75")
            Utility.writePref("RID_uppermissvly_Y", "97.10")
            Utility.writePref("RID_northrockies_X", "42.75")
            Utility.writePref("RID_northrockies_Y", "108.60")
            Utility.writePref("RID_northeast_X", "42.425")
            Utility.writePref("RID_northeast_Y", "74.10")
            Utility.writePref("RID_pacnorthwest_X", "42.425")
            Utility.writePref("RID_pacnorthwest_Y", "120.10")
            Utility.writePref("RID_pacsouthwest_X", "35.15")
            Utility.writePref("RID_pacsouthwest_Y", "120.15")
            Utility.writePref("RID_southrockies_X", "32.5")
            Utility.writePref("RID_southrockies_Y", "110.50")
            Utility.writePref("RID_southplains_X", "31.6")
            Utility.writePref("RID_southplains_Y", "100.00")
            Utility.writePref("RID_southmissvly_X", "31.6")
            Utility.writePref("RID_southmissvly_Y", "90.00")
            Utility.writePref("RID_southeast_X", "29.86")
            Utility.writePref("RID_southeast_Y", "82.658")
            Utility.writePref("RID_hawaii_X", "19.91")
            Utility.writePref("RID_hawaii_Y", "157.55")
            Utility.writePref("RID_iowa_conus_mosaic_X", "37.00")
            Utility.writePref("RID_iowa_conus_mosaic_Y", "96.00")
            Utility.writePref("RID_iowa_mosaic_USCOMP_X", "37.00")
            Utility.writePref("RID_iowa_mosaic_USCOMP_Y", "96.00")
            Utility.writePref("RID_iowa_mosaic_AKCOMP_X", "60.77")
            Utility.writePref("RID_iowa_mosaic_AKCOMP_Y", "150.36")
            Utility.writePref("RID_iowa_mosaic_HICOMP_X", "19.928")
            Utility.writePref("RID_iowa_mosaic_HICOMP_Y", "156.94")
            Utility.writePref("RID_iowa_mosaic_PRCOMP_X", "18.205")
            Utility.writePref("RID_iowa_mosaic_PRCOMP_Y", "66.158")
            Utility.writePref("RID_TDTW_X", "42.11111")
            Utility.writePref("RID_TDTW_Y", "83.515")
            Utility.writePref("RID_TADW_X", "5")
            Utility.writePref("RID_TADW_Y", "5")
            Utility.writePref("RID_TATL_X", "33.646193")
            Utility.writePref("RID_TATL_Y", "84.262233")
            Utility.writePref("RID_TBNA_X", "35.979079")
            Utility.writePref("RID_TBNA_Y", "86.661691")
            Utility.writePref("RID_TBOS_X", "42.15806")
            Utility.writePref("RID_TBOS_Y", "70.93389")
            Utility.writePref("RID_TBWI_X", "39.09056")
            Utility.writePref("RID_TBWI_Y", "76.63")
            Utility.writePref("RID_TLVE_X", "41.289372")
            Utility.writePref("RID_TLVE_Y", "82.007419")
            Utility.writePref("RID_TCLT_X", "35.337269")
            Utility.writePref("RID_TCLT_Y", "80.885006")
            Utility.writePref("RID_TCMH_X", "40.00611")
            Utility.writePref("RID_TCMH_Y", "82.71556")
            Utility.writePref("RID_TCVG_X", "38.89778")
            Utility.writePref("RID_TCVG_Y", "84.58028")
            Utility.writePref("RID_TDAL_X", "32.92494")
            Utility.writePref("RID_TDAL_Y", "96.968473")
            Utility.writePref("RID_TDAY_X", "40.021376")
            Utility.writePref("RID_TDAY_Y", "84.123077")
            Utility.writePref("RID_TDCA_X", "38.758853")
            Utility.writePref("RID_TDCA_Y", "76.961837")
            Utility.writePref("RID_TDEN_X", "39.72722")
            Utility.writePref("RID_TDEN_Y", "104.52639")
            Utility.writePref("RID_TDFW_X", "33.064286")
            Utility.writePref("RID_TDFW_Y", "96.915554")
            Utility.writePref("RID_TEWR_X", "40.593397")
            Utility.writePref("RID_TEWR_Y", "74.270164")
            Utility.writePref("RID_TFLL_X", "26.142601")
            Utility.writePref("RID_TFLL_Y", "80.34382")
            Utility.writePref("RID_THOU_X", "29.515852")
            Utility.writePref("RID_THOU_Y", "95.241692")
            Utility.writePref("RID_TIAD_X", "39.083667")
            Utility.writePref("RID_TIAD_Y", "77.529224")
            Utility.writePref("RID_TIAH_X", "30.06472")
            Utility.writePref("RID_TIAH_Y", "95.5675")
            Utility.writePref("RID_TICT_X", "37.506844")
            Utility.writePref("RID_TICT_Y", "97.437228")
            Utility.writePref("RID_TIDS_X", "39.636556")
            Utility.writePref("RID_TIDS_Y", "86.435286")
            Utility.writePref("RID_TJFK_X", "40.588633")
            Utility.writePref("RID_TJFK_Y", "73.880303")
            Utility.writePref("RID_TLAS_X", "36.144")
            Utility.writePref("RID_TLAS_Y", "115.007")
            Utility.writePref("RID_TMCI_X", "39.49861")
            Utility.writePref("RID_TMCI_Y", "94.74167")
            Utility.writePref("RID_TMCO_X", "28.343125")
            Utility.writePref("RID_TMCO_Y", "81.324674")
            Utility.writePref("RID_TMDW_X", "41.6514")
            Utility.writePref("RID_TMDW_Y", "87.7294")
            Utility.writePref("RID_TMEM_X", "34.896044")
            Utility.writePref("RID_TMEM_Y", "89.992727")
            Utility.writePref("RID_TMIA_X", "25.757083")
            Utility.writePref("RID_TMIA_Y", "80.491076")
            Utility.writePref("RID_TMKE_X", "42.81944")
            Utility.writePref("RID_TMKE_Y", "88.04611")
            Utility.writePref("RID_TMSP_X", "44.870902")
            Utility.writePref("RID_TMSP_Y", "92.932257")
            Utility.writePref("RID_TMSY_X", "30.021389")
            Utility.writePref("RID_TMSY_Y", "90.402919")
            Utility.writePref("RID_TOKC_X", "35.27611")
            Utility.writePref("RID_TOKC_Y", "97.51")
            Utility.writePref("RID_TORD_X", "41.796589")
            Utility.writePref("RID_TORD_Y", "87.857628")
            Utility.writePref("RID_TPBI_X", "26.687812")
            Utility.writePref("RID_TPBI_Y", "80.272931")
            Utility.writePref("RID_TPHL_X", "39.950061")
            Utility.writePref("RID_TPHL_Y", "75.069979")
            Utility.writePref("RID_TPHX_X", "33.420352")
            Utility.writePref("RID_TPHX_Y", "112.16318")
            Utility.writePref("RID_TPIT_X", "40.501066")
            Utility.writePref("RID_TPIT_Y", "80.486586")
            Utility.writePref("RID_TRDU_X", "36.001401")
            Utility.writePref("RID_TRDU_Y", "78.697942")
            Utility.writePref("RID_TSDF_X", "38.04581")
            Utility.writePref("RID_TSDF_Y", "85.610641")
            Utility.writePref("RID_TSJU_X", "18.47394")
            Utility.writePref("RID_TSJU_Y", "66.17891")
            Utility.writePref("RID_TSLC_X", "40.967222")
            Utility.writePref("RID_TSLC_Y", "111.929722")
            Utility.writePref("RID_TSTL_X", "38.804691")
            Utility.writePref("RID_TSTL_Y", "90.488558")
            Utility.writePref("RID_TTPA_X", "27.85867")
            Utility.writePref("RID_TTPA_Y", "82.51755")
            Utility.writePref("RID_TTUL_X", "36.070184")
            Utility.writePref("RID_TTUL_Y", "95.826313")
        }
    }
}
