/*****************************************************************************
 * Copyright (c) 2016, 2017, 2018, 2019 joshua.tee@gmail.com. All rights reserved.
 *
 * Refer to the COPYING file of the official project for license.
 *****************************************************************************/

final class UtilityPref3 {

	static func prefInitRIDLoc() {
		let value = Utility.readPref("RID_LOC_TLVE", "")
		if value == "" {
			Utility.writePref("RID_LOC_iowa_mosaic_AKCOMP", "AK, ")
			Utility.writePref("RID_LOC_iowa_mosaic_PRCOMP", "PR, ")
			Utility.writePref("RID_LOC_iowa_mosaic_HICOMP", "HI, ")
			Utility.writePref("RID_LOC_iowa_mosaic_USCOMP", "CONUS, ")
			Utility.writePref("RID_LOC_alaska", "AK, ")
			Utility.writePref("RID_LOC_NATAK", "AK, ")
			Utility.writePref("RID_LOC_hawaii", "HI, ")
			Utility.writePref("RID_LOC_NATPR", "HI, ")
			Utility.writePref("RID_LOC_pacsouthwest", "pacsouthwest, ")
			Utility.writePref("RID_LOC_pacnorthwest", "pacnorthwest, ")
			Utility.writePref("RID_LOC_southrockies", "southrockies, ")
			Utility.writePref("RID_LOC_northrockies", "northrockies, ")
			Utility.writePref("RID_LOC_southplains", "southplains, ")
			Utility.writePref("RID_LOC_centgrtlakes", "centgrtlakes, ")
			Utility.writePref("RID_LOC_southmissvly", "southmissvly, ")
			Utility.writePref("RID_LOC_uppermissvly", "uppermissvly, ")
			Utility.writePref("RID_LOC_southeast", "southeast, ")
			Utility.writePref("RID_LOC_southeast", "southeast, ")
			Utility.writePref("RID_LOC_conus", "CONUS, ")
			Utility.writePref("RID_LOC_latest", "CONUS, ")
			Utility.writePref("RID_LOC_NAT", "CONUS, ")
			Utility.writePref("RID_LOC_TLVE", "OH, Cleveland")
			Utility.writePref("RID_LOC_TADW", "MD,  Andrews Air Force Base")
			Utility.writePref("RID_LOC_TATL", "GA, Atlanta")
			Utility.writePref("RID_LOC_TBWI", "MD, Baltimore/Wash")
			Utility.writePref("RID_LOC_TBOS", "MA, Boston")
			Utility.writePref("RID_LOC_TCLT", "NC, Charlotte")
			Utility.writePref("RID_LOC_TMDW", "IL, Chicago Midway")
			Utility.writePref("RID_LOC_TORD", "IL, Chicago O'Hare")
			Utility.writePref("RID_LOC_TCLE", "OH, Cleveland")
			Utility.writePref("RID_LOC_TCMH", "OH, Columbus")
			Utility.writePref("RID_LOC_TCVG", "OH, Covington")
			Utility.writePref("RID_LOC_TDAL", "TX, Dallas Love Field")
			Utility.writePref("RID_LOC_TDFW", "TX, Dallas/Ft. Worth")
			Utility.writePref("RID_LOC_TDAY", "OH, Dayton")
			Utility.writePref("RID_LOC_TDEN", "CO, Denver")
			Utility.writePref("RID_LOC_TDTW", "MI, Detroit")
			Utility.writePref("RID_LOC_TIAD", "VA, Dulles")
			Utility.writePref("RID_LOC_TFLL", "FL, Fort Lauderdale")
			Utility.writePref("RID_LOC_THOU", "TX, Houston Hobby")
			Utility.writePref("RID_LOC_TIAH", "TX, Houston International")
			Utility.writePref("RID_LOC_TIDS", "IN, Indianapolis"); // was IDS
			Utility.writePref("RID_LOC_TMCI", "MO, Kansas City")
			Utility.writePref("RID_LOC_TLAS", "NV, Las Vegas")
			Utility.writePref("RID_LOC_TSDF", "KY, Louisville")
			Utility.writePref("RID_LOC_TMEM", "TN, Memphis")
			Utility.writePref("RID_LOC_TMIA", "FL, Miami")
			Utility.writePref("RID_LOC_TMKE", "WI, Milwaukee")
			Utility.writePref("RID_LOC_TMSP", "MN, Minneapolis")
			Utility.writePref("RID_LOC_TBNA", "TN, Nashville")
			Utility.writePref("RID_LOC_TMSY", "LA, New Orleans")
			Utility.writePref("RID_LOC_TJFK", "NY, New York City")
			Utility.writePref("RID_LOC_TEWR", "NJ, Newark")
			Utility.writePref("RID_LOC_TOKC", "OK, Oklahoma City")
			Utility.writePref("RID_LOC_TMCO", "FL, Orlando International")
			Utility.writePref("RID_LOC_TPHL", "PA, Philadelphia")
			Utility.writePref("RID_LOC_TPHX", "AZ, Phoenix")
			Utility.writePref("RID_LOC_TPIT", "PA, Pittsburgh")
			Utility.writePref("RID_LOC_TRDU", "NC, Raleigh Durham")
			Utility.writePref("RID_LOC_TSLC", "UT, Salt Lake City")
			Utility.writePref("RID_LOC_TSJU", "PR, San Juan")
			Utility.writePref("RID_LOC_TSTL", "MO, St Louis")
			Utility.writePref("RID_LOC_TTPA", "FL, Tampa Bay")
			Utility.writePref("RID_LOC_TTUL", "OK, Tulsa")
			Utility.writePref("RID_LOC_TDCA", "MD, Washington National")
			Utility.writePref("RID_LOC_TPBI", "FL, West Palm Beach")
			Utility.writePref("RID_LOC_TICT", "KS, Wichita")
			Utility.writePref("RID_LOC_JUA", "PR, San Juan")
			Utility.writePref("RID_LOC_CBW", "ME, Loring AFB")
			Utility.writePref("RID_LOC_GYX", "ME, Portland")
			Utility.writePref("RID_LOC_CXX", "VT, Burlington")
			Utility.writePref("RID_LOC_BOX", "MA, Boston")
			Utility.writePref("RID_LOC_ENX", "NY, Albany")
			Utility.writePref("RID_LOC_BGM", "NY, Binghamton")
			Utility.writePref("RID_LOC_BUF", "NY, Buffalo")
			Utility.writePref("RID_LOC_TYX", "NY, Montague")
			Utility.writePref("RID_LOC_OKX", "NY, New York City")
			Utility.writePref("RID_LOC_DOX", "DE, Dover AFB")
			Utility.writePref("RID_LOC_DIX", "PA, Philadelphia")
			Utility.writePref("RID_LOC_PBZ", "PA, Pittsburgh")
			Utility.writePref("RID_LOC_CCX", "PA, State College")
			Utility.writePref("RID_LOC_RLX", "WV, Charleston")
			Utility.writePref("RID_LOC_AKQ", "VA, Norfolk/Richmond")
			Utility.writePref("RID_LOC_FCX", "VA, Roanoke")
			Utility.writePref("RID_LOC_LWX", "VA, Sterling")
			Utility.writePref("RID_LOC_MHX", "NC, Morehead City")
			Utility.writePref("RID_LOC_RAX", "NC, Raleigh/Durham")
			Utility.writePref("RID_LOC_LTX", "NC, Wilmington")
			Utility.writePref("RID_LOC_CLX", "SC, Charleston")
			Utility.writePref("RID_LOC_CAE", "SC, Columbia")
			Utility.writePref("RID_LOC_GSP", "SC, Greer")
			Utility.writePref("RID_LOC_FFC", "GA, Atlanta")
			Utility.writePref("RID_LOC_VAX", "GA, Moody AFB")
			Utility.writePref("RID_LOC_JGX", "GA, Robins AFB")
			Utility.writePref("RID_LOC_EVX", "FL, Eglin AFB")
			Utility.writePref("RID_LOC_JAX", "FL, Jacksonville")
			Utility.writePref("RID_LOC_BYX", "FL, Key West")
			Utility.writePref("RID_LOC_MLB", "FL, Melbourne")
			Utility.writePref("RID_LOC_AMX", "FL, Miami")
			Utility.writePref("RID_LOC_TLH", "FL, Tallahassee")
			Utility.writePref("RID_LOC_TBW", "FL, Tampa")
			Utility.writePref("RID_LOC_BMX", "AL, Birmingham")
			Utility.writePref("RID_LOC_EOX", "AL, Fort Rucker")
			Utility.writePref("RID_LOC_HTX", "AL, Huntsville")
			Utility.writePref("RID_LOC_MXX", "AL, Maxwell AFB")
			Utility.writePref("RID_LOC_MOB", "AL, Mobile")
			Utility.writePref("RID_LOC_DGX", "MS, Brandon/Jackson")
			Utility.writePref("RID_LOC_GWX", "MS, Columbus AFB")
			Utility.writePref("RID_LOC_MRX", "TN, Knoxville/Tri Cities")
			Utility.writePref("RID_LOC_NQA", "TN, Memphis")
			Utility.writePref("RID_LOC_OHX", "TN, Nashville")
			Utility.writePref("RID_LOC_HPX", "KY, Fort Campbell")
			Utility.writePref("RID_LOC_JKL", "KY, Jackson")
			Utility.writePref("RID_LOC_LVX", "KY, Louisville")
			Utility.writePref("RID_LOC_PAH", "KY, Paducah")
			Utility.writePref("RID_LOC_ILN", "OH, Wilmington")
			Utility.writePref("RID_LOC_CLE", "OH, Cleveland")
			Utility.writePref("RID_LOC_DTX", "MI, Detroit/Pontiac")
			Utility.writePref("RID_LOC_APX", "MI, Gaylord")
			Utility.writePref("RID_LOC_GRR", "MI, Grand Rapids")
			Utility.writePref("RID_LOC_MQT", "MI, Marquette")
			Utility.writePref("RID_LOC_VWX", "IN, Evansville")
			Utility.writePref("RID_LOC_IND", "IN, Indianapolis")
			Utility.writePref("RID_LOC_IWX", "IN, North Webster")
			Utility.writePref("RID_LOC_LOT", "IL, Chicago")
			Utility.writePref("RID_LOC_ILX", "IL, Lincoln")
			Utility.writePref("RID_LOC_GRB", "WI, Green Bay")
			Utility.writePref("RID_LOC_ARX", "WI, La Crosse")
			Utility.writePref("RID_LOC_MKX", "WI, Milwaukee")
			Utility.writePref("RID_LOC_DLH", "MN, Duluth")
			Utility.writePref("RID_LOC_MPX", "MN, Minneapolis/St. Paul")
			Utility.writePref("RID_LOC_DVN", "IA, Davenport")
			Utility.writePref("RID_LOC_DMX", "IA, Des Moines")
			Utility.writePref("RID_LOC_EAX", "MO, Kansas City")
			Utility.writePref("RID_LOC_SGF", "MO, Springfield")
			Utility.writePref("RID_LOC_LSX", "MO, St. Louis")
			Utility.writePref("RID_LOC_SRX", "AR, Fort Smith")
			Utility.writePref("RID_LOC_LZK", "AR, Little Rock")
			Utility.writePref("RID_LOC_POE", "LA, Fort Polk")
			Utility.writePref("RID_LOC_LCH", "LA, Lake Charles")
			Utility.writePref("RID_LOC_LIX", "LA, New Orleans")
			Utility.writePref("RID_LOC_SHV", "LA, Shreveport")
			Utility.writePref("RID_LOC_AMA", "TX, Amarillo")
			Utility.writePref("RID_LOC_EWX", "TX, Austin/San Antonio")
			Utility.writePref("RID_LOC_BRO", "TX, Brownsville")
			Utility.writePref("RID_LOC_CRP", "TX, Corpus Christi")
			Utility.writePref("RID_LOC_FWS", "TX, Dallas/Ft. Worth")
			Utility.writePref("RID_LOC_DYX", "TX, Dyess AFB")
			Utility.writePref("RID_LOC_EPZ", "TX, El Paso")
			Utility.writePref("RID_LOC_GRK", "TX, Fort Hood")
			Utility.writePref("RID_LOC_HGX", "TX, Houston/Galveston")
			Utility.writePref("RID_LOC_DFX", "TX, Laughlin AFB")
			Utility.writePref("RID_LOC_LBB", "TX, Lubbock")
			Utility.writePref("RID_LOC_MAF", "TX, Midland/Odessa")
			Utility.writePref("RID_LOC_SJT", "TX, San Angelo")
			Utility.writePref("RID_LOC_FDR", "OK, Frederick")
			Utility.writePref("RID_LOC_TLX", "OK, Oklahoma City")
			Utility.writePref("RID_LOC_INX", "OK, Tulsa")
			Utility.writePref("RID_LOC_VNX", "OK, Vance AFB")
			Utility.writePref("RID_LOC_DDC", "KS, Dodge City")
			Utility.writePref("RID_LOC_GLD", "KS, Goodland")
			Utility.writePref("RID_LOC_TWX", "KS, Topeka")
			Utility.writePref("RID_LOC_ICT", "KS, Wichita")
			Utility.writePref("RID_LOC_UEX", "NE, Grand Island/Hastings")
			Utility.writePref("RID_LOC_LNX", "NE, North Platte")
			Utility.writePref("RID_LOC_OAX", "NE, Omaha")
			Utility.writePref("RID_LOC_ABR", "SD, Aberdeen")
			Utility.writePref("RID_LOC_UDX", "SD, Rapid City")
			Utility.writePref("RID_LOC_FSD", "SD, Sioux Falls")
			Utility.writePref("RID_LOC_BIS", "ND, Bismarck")
			Utility.writePref("RID_LOC_MVX", "ND, Grand Forks (Mayville)")
			Utility.writePref("RID_LOC_MBX", "ND, Minot AFB")
			Utility.writePref("RID_LOC_BLX", "MT, Billings")
			Utility.writePref("RID_LOC_GGW", "MT, Glasgow")
			Utility.writePref("RID_LOC_TFX", "MT, Great Falls")
			Utility.writePref("RID_LOC_MSX", "MT, Missoula")
			Utility.writePref("RID_LOC_CYS", "WY, Cheyenne")
			Utility.writePref("RID_LOC_RIW", "WY, Riverton")
			Utility.writePref("RID_LOC_FTG", "CO, Denver")
			Utility.writePref("RID_LOC_GJX", "CO, Grand Junction")
			Utility.writePref("RID_LOC_PUX", "CO, Pueblo")
			Utility.writePref("RID_LOC_ABX", "NM, Albuquerque")
			Utility.writePref("RID_LOC_FDX", "NM, Cannon AFB")
			Utility.writePref("RID_LOC_HDX", "NM, Holloman AFB")
			Utility.writePref("RID_LOC_FSX", "AZ, Flagstaff")
			Utility.writePref("RID_LOC_IWA", "AZ, Phoenix")
			Utility.writePref("RID_LOC_EMX", "AZ, Tucson")
			Utility.writePref("RID_LOC_YUX", "AZ, Yuma")
			Utility.writePref("RID_LOC_ICX", "UT, Cedar City")
			Utility.writePref("RID_LOC_MTX", "UT, Salt Lake City")
			Utility.writePref("RID_LOC_CBX", "ID, Boise")
			Utility.writePref("RID_LOC_SFX", "ID, Pocatello/Idaho Falls")
			Utility.writePref("RID_LOC_LRX", "NV, Elko")
			Utility.writePref("RID_LOC_ESX", "NV, Las Vegas")
			Utility.writePref("RID_LOC_RGX", "NV, Reno")
			Utility.writePref("RID_LOC_BBX", "CA, Beale AFB")
			Utility.writePref("RID_LOC_EYX", "CA, Edwards AFB")
			Utility.writePref("RID_LOC_BHX", "CA, Eureka")
			Utility.writePref("RID_LOC_VTX", "CA, Los Angeles")
			Utility.writePref("RID_LOC_DAX", "CA, Sacramento")
			Utility.writePref("RID_LOC_NKX", "CA, San Diego")
			Utility.writePref("RID_LOC_MUX", "CA, San Francisco")
			Utility.writePref("RID_LOC_HNX", "CA, San Joaquin Valley")
			Utility.writePref("RID_LOC_SOX", "CA, Santa Ana Mountains")
			Utility.writePref("RID_LOC_VBX", "CA, Vandenberg AFB")
			Utility.writePref("RID_LOC_HKI", "HI, Kauai")
			Utility.writePref("RID_LOC_HKM", "HI, Kohala")
			Utility.writePref("RID_LOC_HMO", "HI, Molokai")
			Utility.writePref("RID_LOC_HWA", "HI, South Shore")
			Utility.writePref("RID_LOC_MAX", "OR, Medford")
			Utility.writePref("RID_LOC_PDT", "OR, Pendleton")
			Utility.writePref("RID_LOC_RTX", "OR, Portland")
			Utility.writePref("RID_LOC_LGX", "WA, Langley Hill")
			Utility.writePref("RID_LOC_ATX", "WA, Seattle/Tacoma")
			Utility.writePref("RID_LOC_OTX", "WA, Spokane")
			Utility.writePref("RID_LOC_ABC", "AK, Bethel")
			Utility.writePref("RID_LOC_APD", "AK, Fairbanks/Pedro Dome")
			Utility.writePref("RID_LOC_AHG", "AK, Kenai")
			Utility.writePref("RID_LOC_AKC", "AK, King Salmon")
			Utility.writePref("RID_LOC_AIH", "AK, Middleton Island")
			Utility.writePref("RID_LOC_AEC", "AK, Nome")
			Utility.writePref("RID_LOC_ACG", "AK, Sitka/Biorka Island")
			Utility.writePref("RID_LOC_GUA", "GU, Andersen AFB")
			Utility.writePref("RID_LOC_PLA", "NA, Lajes Field, Azores")
			Utility.writePref("RID_LOC_KJK", "NA, Kunsan Air Base, South Korea")
			Utility.writePref("RID_LOC_KSG", "NA, Camp Humphreys, South Korea")
			Utility.writePref("RID_LOC_ODN", "NA, Kadena Air Base, Japan")
		}
	}
}
