/*****************************************************************************
 * Copyright (c) 2016, 2017, 2018, 2019, 2020 joshua.tee@gmail.com. All rights reserved.
 *
 * Refer to the COPYING file of the official project for license.
 *****************************************************************************/

final class UtilityPref4 {

    static func prefInitSoundingSitesLoc() {
        let value = Utility.readPref("SND_IAD_X", "")
        if value == "" {
            Utility.writePref("SND_1Y7_X", "32.87")
            Utility.writePref("SND_1Y7_Y", "114.40")
            Utility.writePref("SND_76405_X", "24.07")
            Utility.writePref("SND_76405_Y", "110.33")
            Utility.writePref("SND_76458_X", "23.18")
            Utility.writePref("SND_76458_Y", "106.42")
            Utility.writePref("SND_VBG_X", "34.72")
            Utility.writePref("SND_VBG_Y", "120.57")
            Utility.writePref("SND_ABR_X", "45.45")
            Utility.writePref("SND_ABR_Y", "98.41")
            Utility.writePref("SND_ALB_X", "42.75")
            Utility.writePref("SND_ALB_Y", "73.80")
            Utility.writePref("SND_ABQ_X", "35.03")
            Utility.writePref("SND_ABQ_Y", "106.62")
            Utility.writePref("SND_AMA_X", "35.23")
            Utility.writePref("SND_AMA_Y", "101.70")
            Utility.writePref("SND_BIS_X", "46.77")
            Utility.writePref("SND_BIS_Y", "100.75")
            Utility.writePref("SND_RNK_X", "37.21")
            Utility.writePref("SND_RNK_Y", "80.41")
            Utility.writePref("SND_BOI_X", "43.57")
            Utility.writePref("SND_BOI_Y", "116.22")
            Utility.writePref("SND_BRO_X", "25.90")
            Utility.writePref("SND_BRO_Y", "97.43")
            Utility.writePref("SND_BUF_X", "42.93")
            Utility.writePref("SND_BUF_Y", "78.73")
            Utility.writePref("SND_CAR_X", "46.87")
            Utility.writePref("SND_CAR_Y", "68.02")
            Utility.writePref("SND_ILX_X", "40.10")
            Utility.writePref("SND_ILX_Y", "89.30")
            Utility.writePref("SND_CHS_X", "32.90")
            Utility.writePref("SND_CHS_Y", "80.03")
            Utility.writePref("SND_MPX_X", "44.85")
            Utility.writePref("SND_MPX_Y", "93.57")
            Utility.writePref("SND_CHH_X", "41.67")
            Utility.writePref("SND_CHH_Y", "69.97")
            Utility.writePref("SND_CRP_X", "27.77")
            Utility.writePref("SND_CRP_Y", "97.50")
            Utility.writePref("SND_DRT_X", "29.37")
            Utility.writePref("SND_DRT_Y", "100.92")
            Utility.writePref("SND_DRA_X", "36.62")
            Utility.writePref("SND_DRA_Y", "116.02")
            Utility.writePref("SND_DNR_X", "39.75")
            Utility.writePref("SND_DNR_Y", "104.87")
            Utility.writePref("SND_DDC_X", "37.77")
            Utility.writePref("SND_DDC_Y", "99.97")
            Utility.writePref("SND_LKN_X", "40.87")
            Utility.writePref("SND_LKN_Y", "115.73")
            Utility.writePref("SND_EPZ_X", "31.90")
            Utility.writePref("SND_EPZ_Y", "106.70")
            Utility.writePref("SND_FLG_X", "35.23")
            Utility.writePref("SND_FLG_Y", "111.82")
            Utility.writePref("SND_FWD_X", "32.80")
            Utility.writePref("SND_FWD_Y", "97.30")
            Utility.writePref("SND_APX_X", "44.90")
            Utility.writePref("SND_APX_Y", "84.72")
            Utility.writePref("SND_GGW_X", "48.21")
            Utility.writePref("SND_GGW_Y", "106.63")
            Utility.writePref("SND_GJT_X", "39.12")
            Utility.writePref("SND_GJT_Y", "108.53")
            Utility.writePref("SND_GYX_X", "43.89")
            Utility.writePref("SND_GYX_Y", "70.25")
            Utility.writePref("SND_TFX_X", "47.45")
            Utility.writePref("SND_TFX_Y", "111.38")
            Utility.writePref("SND_GRB_X", "44.48")
            Utility.writePref("SND_GRB_Y", "88.13")
            Utility.writePref("SND_GSO_X", "36.08")
            Utility.writePref("SND_GSO_Y", "79.95")
            Utility.writePref("SND_INL_X", "48.57")
            Utility.writePref("SND_INL_Y", "93.38")
            Utility.writePref("SND_JAN_X", "32.32")
            Utility.writePref("SND_JAN_Y", "90.08")
            Utility.writePref("SND_JAX_X", "30.43")
            Utility.writePref("SND_JAX_Y", "81.61")
            Utility.writePref("SND_EYW_X", "24.55")
            Utility.writePref("SND_EYW_Y", "81.75")
            Utility.writePref("SND_LCH_X", "30.12")
            Utility.writePref("SND_LCH_Y", "93.22")
            Utility.writePref("SND_LZK_X", "34.83")
            Utility.writePref("SND_LZK_Y", "92.25")
            Utility.writePref("SND_MFR_X", "42.37")
            Utility.writePref("SND_MFR_Y", "122.87")
            Utility.writePref("SND_MFX_X", "25.80")
            Utility.writePref("SND_MFX_Y", "80.38")
            Utility.writePref("SND_MAF_X", "31.95")
            Utility.writePref("SND_MAF_Y", "102.18")
            Utility.writePref("SND_BNA_X", "36.12")
            Utility.writePref("SND_BNA_Y", "86.68")
            Utility.writePref("SND_MHX_X", "34.70")
            Utility.writePref("SND_MHX_Y", "76.80")
            Utility.writePref("SND_OUN_X", "35.23")
            Utility.writePref("SND_OUN_Y", "97.47")
            Utility.writePref("SND_LBF_X", "41.13")
            Utility.writePref("SND_LBF_Y", "100.68")
            Utility.writePref("SND_OAK_X", "37.73")
            Utility.writePref("SND_OAK_Y", "122.22")
            Utility.writePref("SND_FFC_X", "33.36")
            Utility.writePref("SND_FFC_Y", "84.56")
            Utility.writePref("SND_PIT_X", "40.50")
            Utility.writePref("SND_PIT_Y", "80.22")
            Utility.writePref("SND_DVN_X", "41.60")
            Utility.writePref("SND_DVN_Y", "90.60")
            Utility.writePref("SND_UIL_X", "47.95")
            Utility.writePref("SND_UIL_Y", "124.55")
            Utility.writePref("SND_UNR_X", "44.07")
            Utility.writePref("SND_UNR_Y", "103.21")
            Utility.writePref("SND_REV_X", "39.57")
            Utility.writePref("SND_REV_Y", "119.80")
            Utility.writePref("SND_RIW_X", "43.00")
            Utility.writePref("SND_RIW_Y", "108.50")
            Utility.writePref("SND_SLE_X", "44.92")
            Utility.writePref("SND_SLE_Y", "123.00")
            Utility.writePref("SND_SLC_X", "40.78")
            Utility.writePref("SND_SLC_Y", "111.97")
            Utility.writePref("SND_NKX_X", "32.73")
            Utility.writePref("SND_NKX_Y", "117.17")
            Utility.writePref("SND_BMX_X", "33.17")
            Utility.writePref("SND_BMX_Y", "86.77")
            Utility.writePref("SND_SHV_X", "32.45")
            Utility.writePref("SND_SHV_Y", "93.83")
            Utility.writePref("SND_SIL_X", "30.25")
            Utility.writePref("SND_SIL_Y", "89.77")
            Utility.writePref("SND_OTX_X", "47.68")
            Utility.writePref("SND_OTX_Y", "117.63")
            Utility.writePref("SND_SGF_X", "37.14")
            Utility.writePref("SND_SGF_Y", "93.23")
            Utility.writePref("SND_LWX_X", "38.98")
            Utility.writePref("SND_LWX_Y", "77.47")
            Utility.writePref("SND_NJM_X", "34.69")
            Utility.writePref("SND_NJM_Y", "77.03")
            Utility.writePref("SND_TLH_X", "30.56")
            Utility.writePref("SND_TLH_Y", "84.45")
            Utility.writePref("SND_TBW_X", "27.70")
            Utility.writePref("SND_TBW_Y", "82.40")
            Utility.writePref("SND_TOP_X", "39.07")
            Utility.writePref("SND_TOP_Y", "95.62")
            Utility.writePref("SND_TUS_X", "32.12")
            Utility.writePref("SND_TUS_Y", "110.93")
            Utility.writePref("SND_OKX_X", "40.86")
            Utility.writePref("SND_OKX_Y", "72.86")
            Utility.writePref("SND_OAX_X", "41.32")
            Utility.writePref("SND_OAX_Y", "96.37")
            Utility.writePref("SND_WAL_X", "37.85")
            Utility.writePref("SND_WAL_Y", "75.48")
            Utility.writePref("SND_DTX_X", "42.68")
            Utility.writePref("SND_DTX_Y", "83.47")
            Utility.writePref("SND_ILN_X", "39.42")
            Utility.writePref("SND_ILN_Y", "83.82")
            Utility.writePref("SND_ASY_X", "52.72")
            Utility.writePref("SND_ASY_Y", "174.12")
            Utility.writePref("SND_ASN_X", "57.15")
            Utility.writePref("SND_ASN_Y", "170.22")
            Utility.writePref("SND_ACD_X", "55.20")
            Utility.writePref("SND_ACD_Y", "162.73")
            Utility.writePref("SND_ANT_X", "55.03")
            Utility.writePref("SND_ANT_Y", "131.57")
            Utility.writePref("SND_AYA_X", "59.52")
            Utility.writePref("SND_AYA_Y", "139.67")
            Utility.writePref("SND_ANC_X", "61.17")
            Utility.writePref("SND_ANC_Y", "150.02")
            Utility.writePref("SND_ADQ_X", "57.75")
            Utility.writePref("SND_ADQ_Y", "152.50")
            Utility.writePref("SND_AKN_X", "58.68")
            Utility.writePref("SND_AKN_Y", "156.65")
            Utility.writePref("SND_ABE_X", "60.78")
            Utility.writePref("SND_ABE_Y", "161.80")
            Utility.writePref("SND_AMC_X", "62.95")
            Utility.writePref("SND_AMC_Y", "155.60")
            Utility.writePref("SND_AFA_X", "64.82")
            Utility.writePref("SND_AFA_Y", "147.87")
            Utility.writePref("SND_AOM_X", "64.52")
            Utility.writePref("SND_AOM_Y", "165.45")
            Utility.writePref("SND_AOT_X", "66.87")
            Utility.writePref("SND_AOT_Y", "162.63")
            Utility.writePref("SND_KEY_X", "24.55")
            Utility.writePref("SND_KEY_Y", "81.75")
            Utility.writePref("SND_MFL_X", "25.75")
            Utility.writePref("SND_MFL_Y", "80.38")
            Utility.writePref("SND_YLW_X", "49.97")
            Utility.writePref("SND_YLW_Y", "119.38")
            Utility.writePref("SND_WPL_X", "51.47")
            Utility.writePref("SND_WPL_Y", "90.20")
            Utility.writePref("SND_YMO_X", "51.27")
            Utility.writePref("SND_YMO_Y", "80.65")
            Utility.writePref("SND_WMW_X", "46.0")
            Utility.writePref("SND_WMW_Y", "76.87")
            Utility.writePref("SND_76225_X", "28.70")
            Utility.writePref("SND_76225_Y", "106.07")
            Utility.writePref("SND_LIX_X", "30.337")
            Utility.writePref("SND_LIX_Y", "89.825")
            Utility.writePref("SND_IAD_X", "39.083667")
            Utility.writePref("SND_IAD_Y", "77.529224")
        }
    }

    static func prefInitSoundingSites() {
        let value = Utility.readPref("NWS_SOUNDINGLOCATION_VBG", "")
        if value == "" {
            Utility.writePref("NWS_SOUNDINGLOCATION_VBG", "CA, Vandenberg AFB")
            Utility.writePref("NWS_SOUNDINGLOCATION_1Y7", "AZ, Yuma")
            Utility.writePref("NWS_SOUNDINGLOCATION_76405", "MX, La Paz")
            Utility.writePref("NWS_SOUNDINGLOCATION_76458", "MX, Mazatlan")
            Utility.writePref("NWS_SOUNDINGLOCATION_SLE", "OR, Salem")
            Utility.writePref("NWS_SOUNDINGLOCATION_UIL", "WA, Quillayute")
            Utility.writePref("NWS_SOUNDINGLOCATION_YLW", ", KELOWNA APT")
            Utility.writePref("NWS_SOUNDINGLOCATION_OAK", "CA, Oakland")
            Utility.writePref("NWS_SOUNDINGLOCATION_NKX", "CA, San Diego")
            Utility.writePref("NWS_SOUNDINGLOCATION_TUS", "AZ, Tucson")
            Utility.writePref("NWS_SOUNDINGLOCATION_DRT", "TX, Del Rio")
            Utility.writePref("NWS_SOUNDINGLOCATION_RAP", "SD, Rapid City")
            Utility.writePref("NWS_SOUNDINGLOCATION_INL", "MN, International Falls")
            Utility.writePref("NWS_SOUNDINGLOCATION_BNA", "TN, Nashville")
            Utility.writePref("NWS_SOUNDINGLOCATION_YMO", ", MOOSONEE")
            Utility.writePref("NWS_SOUNDINGLOCATION_GSO", "NC, Greensboro")
            Utility.writePref("NWS_SOUNDINGLOCATION_WAL", "VA, Wallops Island")
            Utility.writePref("NWS_SOUNDINGLOCATION_IAD", "DC, Washington")
            Utility.writePref("NWS_SOUNDINGLOCATION_PIT", "PA, Pittsburgh")
            Utility.writePref("NWS_SOUNDINGLOCATION_ALB", "NY, Albany")
            Utility.writePref("NWS_SOUNDINGLOCATION_CHH", "MA, Chatham")
            Utility.writePref("NWS_SOUNDINGLOCATION_YQI", "Nova Scotia, Yarmouth")
            Utility.writePref("NWS_SOUNDINGLOCATION_XMR", "FL, Cape Canaveral")
            Utility.writePref("NWS_SOUNDINGLOCATION_TLH", "FL, Tallahassee")
            Utility.writePref("NWS_SOUNDINGLOCATION_WPL", "ON, Pickle Lake")
            Utility.writePref("NWS_SOUNDINGLOCATION_DNR", "CO, Denver")
        }
    }
}
