/*****************************************************************************
 * Copyright (c) 2016, 2017, 2018 joshua.tee@gmail.com. All rights reserved.
 *
 * Refer to the COPYING file of the official project for license.
 *****************************************************************************/

class R {

    static let pre = ""

    class Raw {
        static let hw = pre + "hw"
        static let hwv4 = pre + "hwv4"
        static let hwv4ext = pre + "hwv4ext"
        static let lakesv3 = pre + "lakesv3"
        static let county = pre + "county"
        static let countyv2 = pre + "countyv2"
        static let statev3 = pre + "statev3"
        static let statev2 = pre + "statev2"
        static let mx = pre + "mx"
        static let ca = pre + "ca"
        static let cityall = pre + "cityall.txt"
        static let gaz_counties_national = pre + "gaz_counties_national.txt"
        static let stations_us4 = pre + "stations_us4.txt"
        static let colormaprefdkenh = pre + "colormaprefdkenh.txt"
        static let colormaprefcode = pre + "colormaprefcode.txt"
        static let colormaprefnssl = pre + "colormaprefnssl.txt"
        static let colormaprefnwsd = pre + "colormaprefnwsd.txt"
        static let colormaprefcodenh = pre + "colormaprefcodenh.txt"
        static let colormaprefmenh = pre + "colormaprefmenh.txt"
        static let colormaprefgreen = pre + "colormaprefgreen.txt"
        static let colormaprefaf = pre + "colormaprefaf.txt"
        static let colormaprefeak = pre + "colormaprefeak.txt"
        static let colormapbvcod = pre + "colormapbvcod.txt"
        static let colormapbvaf = pre + "colormapbvaf.txt"
        static let colormapbveak = pre + "colormapbveak.txt"
        static let colormap135cod = pre + "colormap135cod.txt"
        static let colormap161cod = pre + "colormap161cod.txt"
        static let colormap163cod = pre + "colormap163cod.txt"
        static let colormap159cod = pre + "colormap159cod.txt"
        static let colormap134cod = pre + "colormap134cod.txt"
        static let colormap165cod = pre + "colormap165cod.txt"
        static let colormap172cod = pre + "colormap172cod.txt"
        static let us_metar3 = pre + "us_metar3.txt"
        static let dvn94 = pre + "dvn94.bin"
        static let dvn99 = pre + "dvn99.bin"
    }

    class Drawable {
        static let bkn = "bkn.png"
        static let blizzard = "blizzard.png"
        static let cold = "cold.png"
        static let du = "du.png"
        static let fc = "fc.png"
        static let few = "few.png"
        static let fg = "fg.png"
        static let fu = "fu.png"
        static let fzra = "fzra.png"
        static let fzra_sn = "fzra_sn.png"
        static let hi_nshwrs = "hi_nshwrs.png"
        static let hi_ntsra = "hi_ntsra.png"
        static let hi_shwrs = "hi_shwrs.png"
        static let hi_tsra = "hi_tsra.png"
        static let hot = "hot.png"
        static let hz = "hz.png"
        static let ip = "ip.png"
        static let nbkn = "nbkn.png"
        static let nblizzard = "nblizzard.png"
        static let ncold = "ncold.png"
        static let ndu = "ndu.png"
        static let nfc = "nfc.png"
        static let nfew = "nfew.png"
        static let nfg = "nfg.png"
        static let nfu = "nfu.png"
        static let nfzra = "nfzra.png"
        static let nfzra_sn = "nfzra_sn.png"
        static let nip = "nip.png"
        static let novc = "novc.png"
        static let nra_fzra = "nra_fzra.png"
        static let nraip = "nraip.png"
        static let nra = "nra.png"
        static let nra_sn = "nra_sn.png"
        static let nsct = "nsct.png"
        static let nscttsra = "nscttsra.png"
        static let nshra = "nshra.png"
        static let nskc = "nskc.png"
        static let nsn = "nsn.png"
        static let ntor = "ntor.png"
        static let ntsra = "ntsra.png"
        static let nwind_bkn = "nwind_bkn.png"
        static let nwind_few = "nwind_few.png"
        static let nwind_ovc = "nwind_ovc.png"
        static let nwind_sct = "nwind_sct.png"
        static let nwind_skc = "nwind_skc.png"
        static let ovc = "ovc.png"
        static let ra_fzra = "ra_fzra.png"
        static let raip = "raip.png"
        static let ra = "ra.png"
        static let ra_sn = "ra_sn.png"
        static let sct = "sct.png"
        static let scttsra = "scttsra.png"
        static let shra = "shra.png"
        static let skc = "skc.png"
        static let sn = "sn.png"
        static let tor = "tor.png"
        static let tsra = "tsra.png"
        static let wind_bkn = "wind_bkn.png"
        static let wind_few = "wind_few.png"
        static let wind_ovc = "wind_ovc.png"
        static let wind_sct = "wind_sct.png"
        static let wind_skc = "wind_skc.png"
        static let sn_ip = "sn_ip.png"
        static let nsn_ip = "nsn_ip.png"
        static let rasn = "rasn.png"
        static let nrasn = "nrasn.png"
        static let hurr = "hurr.png"
        static let hurr_noh = "hurr-noh.png"
        static let tropstorm = "tropstorm.png"
        static let tropstorm_noh = "tropstorm_noh.png"
        static let ntropstorm_noh = "tropstorm_noh.png"
        static let nmix = "nmix.png"
        static let mix = "mix.png"
        static let ts = "ts.png"
        static let ts_hur_flags = "ts_hur_flags.png"
        static let ic_report_24dp = "ic_report_24dp"
        static let ic_public_24dp = "ic_public_24dp"
        static let ic_brightness_7_24dp = "ic_brightness_7_24dp"
        static let ic_flash_off_24dp = "ic_flash_off_24dp"
        static let ic_directions_24dp = "ic_directions_24dp"
        static let ic_play_arrow_24dp = "ic_play_arrow_24dp"
        static let ic_warning_24dp = "ic_warning_24dp"
        static let ic_flash_on_24dp = "ic_flash_on_24dp"
        static let ic_place_24dp = "ic_place_24dp"
        static let ic_info_outline_24dp = "ic_info_outline_24dp"
        static let ic_brightness_auto_24dp = "ic_brightness_auto_24dp"
        static let ic_brightness_medium_24dp = "ic_brightness_medium_24dp"
        static let ic_delete_24dp = "ic_delete_24dp"
        static let ic_star_24dp = "ic_star_24dp"
        static let ic_star_outline_24dp = "ic_star_outline_24dp"
        static let ic_stop_24dp = "ic_stop_24dp"
        static let ic_mic_24dp = "ic_mic_24dp"
        static let ic_pause_24dp = "ic_pause_24dp"
        static let ic_pause_white_24dp = "ic_pause_white_24dp"
        static let ic_keyboard_arrow_up_24dp = "ic_keyboard_arrow_up_24dp"
        static let ic_keyboard_arrow_down_24dp = "ic_keyboard_arrow_down_24dp"
        static let ic_add_box_24dp = "ic_add_box_24dp"
        static let ic_keyboard_arrow_left_24dp = "ic_keyboard_arrow_left_24dp"
        static let ic_keyboard_arrow_right_24dp = "ic_keyboard_arrow_right_24dp"
        static let ic_skip_previous_24dp = "ic_skip_previous_24dp"
        static let ic_skip_next_24dp = "ic_skip_next_24dp"
        static let minus_ra = "minus_ra.png"
        static let nminus_ra = "nminus_ra.png"
        static let nhi_tsra = "nhi_tsra.png"
    }
}
